table 'public employee_absences'
	lineageTag: 9e77a967-8955-4ac0-99b9-d5107489b212

	measure 'Bradford Factor 2021' = SUM('public employee_absences'[Year BF 2021]) *SUM('public employee_absences'[Year BF 2021])*SUM('public employee_absences'[Duration 2021])
		formatString: 0
		lineageTag: d4ae01a9-38be-483c-a9a3-4ca5df35f375

	measure 'Bradford Factor average FU 2021' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('public employee_absences'[person_number] )),
				CALCULATE([Bradford Factor 2021])
			)
		formatString: 0
		lineageTag: e9674d0d-dd6d-4489-b92d-c90884cd3709

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "AveragePerCategory"
				}

	measure 'Sum Person number' = SUM('public employee_absences'[Person count])
		formatString: 0
		lineageTag: 854d49f7-ab0e-493b-b873-3640fd526743

	measure avg_Unplanned_per_bufu = CALCULATE(SUM('public employee_absences'[Unplanned])/DISTINCTCOUNT('public employee_absences'[person_number]),ALLEXCEPT('public employee_absences','public employees'[parent_entity],'public employees'[bu_fu]))
		lineageTag: 64c525e9-9851-4c8f-90de-b3d0337fd433

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unplanned average per bu_fu' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('public employee_absences'[person_number] )),
				CALCULATE([Sum Unplanned])
			)
		lineageTag: f3fd429a-4916-450a-a1c2-e63e1b2fde4d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum Unplanned' = SUM('public employee_absences'[Unplanned])
		formatString: 0
		lineageTag: 0c6088d7-cbe6-446d-b543-da650d8c1d87

	measure 'Sum Leave Planned' = SUM('public employee_absences'[Leave p])
		formatString: 0
		lineageTag: 2607be70-c10e-4663-a968-3ad97205d6a1

	measure 'Planned average per bu_fu' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('public employee_absences'[person_number] )),
				CALCULATE([Sum Leave Planned])
			)
		lineageTag: ded238f3-ea04-426e-8cdc-b0bde8d2bf47

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bradford Factor 2020' = SUM('public employee_absences'[Year BF 2020]) *SUM('public employee_absences'[Year BF 2020])*SUM('public employee_absences'[Duration 2020])
		lineageTag: 5bf688ce-bc4a-477f-8434-8f1a4939f47f

	measure 'Bradford Factor average FU 2020' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('public employee_absences'[person_number] )),
				CALCULATE([Bradford Factor 2020])
			)
		lineageTag: a4c011c2-aa75-4fa3-bbe3-49d5514e29b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum unplanned duration' = SUM('public employee_absences'[unplanned duration])
		formatString: 0
		lineageTag: b40908a5-916b-4e8f-b647-63bf6bff6464

	measure 'unplanned duration average per bu_fu' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('public employee_absences'[person_number] )),
				CALCULATE([Sum unplanned duration])
			)
		lineageTag: e288cae4-888f-4e60-adcd-7440e3d0233d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum planned duration' = SUM('public employee_absences'[planned duration])
		formatString: 0
		lineageTag: 0c9c7f0b-bc57-49f1-bfa6-cf234befd261

	measure 'planned duration average per bu_fu' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('public employee_absences'[person_number] )),
				CALCULATE([Sum planned duration])
			)
		lineageTag: a2cd8a92-f399-4160-8895-94b5da7018f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bradford Factor 2022' = SUM('public employee_absences'[Year BF 2022]) *SUM('public employee_absences'[Year BF 2022])*SUM('public employee_absences'[Duration 2022])
		formatString: 0
		lineageTag: 425a9854-c5fe-4c75-8693-ed9936821104

	measure 'Bradford Factor 2023' = SUM('public employee_absences'[Year BF 2023]) *SUM('public employee_absences'[Year BF 2023])*SUM('public employee_absences'[Duration 2023])
		formatString: 0
		lineageTag: 2cabc7d2-7826-41c1-808a-923c7d867165

	measure 'Bradford Factor average FU 2022' = ```
			
			AVERAGEX(
			    KEEPFILTERS(VALUES('public employee_absences'[person_number] )),
			    CALCULATE([Bradford Factor 2022])
			)
			
			```
		lineageTag: 8d64b6a9-bf1b-4cc4-9ae0-f88e5ae8ecf2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bradford Factor average FU 2023' = ```
			
			AVERAGEX(
			    KEEPFILTERS(VALUES('public employee_absences'[person_number] )),
			    CALCULATE([Bradford Factor 2023])
			)
			
			```
		lineageTag: 7f41ad13-8829-41d2-866f-89de8ffda41c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column person_number
		dataType: string
		lineageTag: 52a62077-5d66-4462-a6e0-9ad9f30dbd9a
		summarizeBy: none
		sourceColumn: person_number

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: a35f1a16-0b4a-4336-96ed-c8aec669cdb7
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: string
		lineageTag: 96f81f5e-8b6c-430c-a3be-d2c2c65eb6e7
		summarizeBy: none
		sourceColumn: duration

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: string
		lineageTag: 7209a033-09b0-4a71-b521-49de88cb7bf4
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: string
		lineageTag: 96c3fec8-ab6d-4ef7-94e5-2014493d9daa
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

	column 'person_number.1'
		dataType: string
		lineageTag: 0640c3c4-f750-4199-bbe2-04954e0662a7
		summarizeBy: none
		sourceColumn: person_number.1

		annotation SummarizationSetBy = Automatic

	column absence_type
		dataType: string
		lineageTag: 46644d06-b3c3-4f97-9786-210f6f3f465b
		summarizeBy: none
		sourceColumn: absence_type

		annotation SummarizationSetBy = Automatic

	column reason
		dataType: string
		lineageTag: ee25dff8-498f-4b8c-b29e-d6870a7032d9
		summarizeBy: none
		sourceColumn: reason

		annotation SummarizationSetBy = Automatic

	column absence_name
		dataType: string
		lineageTag: 765d2cd5-3201-4e5c-848b-195d490e30b8
		summarizeBy: none
		sourceColumn: absence_name

		annotation SummarizationSetBy = Automatic

	column balance
		dataType: string
		lineageTag: 44a8db30-ef2e-4cae-8ef1-58acd0fcf2c8
		summarizeBy: none
		sourceColumn: balance

		annotation SummarizationSetBy = Automatic

	column planned
		dataType: string
		lineageTag: ccb048f4-5512-436c-ac1e-288e604383b3
		summarizeBy: none
		sourceColumn: planned

		annotation SummarizationSetBy = Automatic

	column ori
		dataType: string
		lineageTag: 04170378-320e-4ae7-8a85-8c7dddcdb2e7
		summarizeBy: none
		sourceColumn: ori

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: 50bf39e8-a264-41de-90e0-68d3f8603362
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column 'Total Absence days'
		dataType: string
		lineageTag: 9afb9209-631a-41fe-981b-7edaf1f8ff9b
		summarizeBy: none
		sourceColumn: Total Absence days

		annotation SummarizationSetBy = Automatic

	column 'Year BF'
		dataType: string
		lineageTag: f375bfcc-5aef-433c-a12d-a44867e6626b
		summarizeBy: none
		sourceColumn: Year BF

		annotation SummarizationSetBy = Automatic

	column 'Year BF 2021'
		dataType: int64
		formatString: 0
		lineageTag: c49b8bbc-cb1f-48ca-b558-481130388873
		summarizeBy: sum
		sourceColumn: Year BF 2021

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column 'Year BF 2020'
		dataType: int64
		formatString: 0
		lineageTag: ac2d3881-d608-4b01-8461-104b0169b1b9
		summarizeBy: sum
		sourceColumn: Year BF 2020

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column 'Duration 2021'
		dataType: int64
		formatString: 0
		lineageTag: 088de21b-dda3-4e5e-9f6f-00c242775431
		summarizeBy: sum
		sourceColumn: Duration 2021

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column Index
		dataType: string
		lineageTag: 20433bd4-3367-44c3-836f-9a5e721a114f
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Unplanned
		dataType: int64
		formatString: 0
		lineageTag: b02ca2ed-e98d-4cf7-8446-02096f50cd40
		summarizeBy: sum
		sourceColumn: Unplanned

		annotation SummarizationSetBy = User

		annotation PBI_ChangedProperties = ["DataType"]

	column 'Total Absence days - Copy'
		dataType: dateTime
		lineageTag: 33b0ab5a-b01d-4096-856a-e55208a53836
		summarizeBy: none
		sourceColumn: Total Absence days - Copy

		variation Variation
			isDefault
			relationship: aa1f86d7-8fe7-43a7-ae3d-a89ac292a187
			defaultHierarchy: LocalDateTable_2a9e4b86-65eb-4eb1-bfdd-29d0df1a8547.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["DataType"]

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: c7818223-69d4-4963-a507-831b49da8ce9
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Total Absence days - Copy - Copy'
		dataType: dateTime
		lineageTag: ab645746-7115-4873-b828-e2282dd1545f
		summarizeBy: none
		sourceColumn: Total Absence days - Copy - Copy

		variation Variation
			isDefault
			relationship: 599938aa-1a8e-4d54-aa4b-a77902b98927
			defaultHierarchy: LocalDateTable_c4194097-caf7-413b-8ab9-5e64b40e7058.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_ChangedProperties = ["DataType"]

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 3aed591c-43b8-451d-bf66-60df8f38420c
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Planned 2'
		dataType: string
		lineageTag: 9ce8f341-ea4e-442a-a7e4-41e4c5f0a856
		summarizeBy: none
		sourceColumn: Planned

		annotation SummarizationSetBy = Automatic

	column 'Leave p'
		dataType: int64
		formatString: 0
		lineageTag: 1a2b5c21-2f1d-428e-a6ec-d8f74c2b09f8
		summarizeBy: sum
		sourceColumn: Leave p

		annotation SummarizationSetBy = User

		annotation PBI_ChangedProperties = ["DataType"]

	column 'Month name'
		dataType: string
		lineageTag: 83755adb-607b-4775-b773-c490e51fa33d
		summarizeBy: none
		sourceColumn: Month name

		annotation SummarizationSetBy = Automatic

	column 'Person count'
		dataType: int64
		formatString: 0
		lineageTag: 0b59d08f-6380-4e6a-9220-9f708bec98ca
		summarizeBy: distinctCount
		sourceColumn: Person count

		annotation SummarizationSetBy = User

	column 'Balance balance'
		dataType: int64
		formatString: 0
		lineageTag: 35672f03-3788-4b66-96f0-d84e7a225653
		summarizeBy: sum
		sourceColumn: Balance balance

		annotation SummarizationSetBy = Automatic

	column 'Balance count'
		dataType: int64
		formatString: 0
		lineageTag: ada0ec97-1fc7-4175-9d5f-0b436b752178
		summarizeBy: sum
		sourceColumn: Balance count

		annotation SummarizationSetBy = Automatic

	column 'planned - Copy'
		dataType: string
		lineageTag: 511ffa5d-02b1-4e45-8f8e-0ceed9268621
		summarizeBy: none
		sourceColumn: planned - Copy

		annotation SummarizationSetBy = Automatic

	column 'Planned number'
		dataType: int64
		formatString: 0
		lineageTag: 457c0b40-2ec4-400b-96a4-83a809bd026a
		summarizeBy: sum
		sourceColumn: Planned number

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column 'Absence reason'
		dataType: string
		lineageTag: b3e14bf1-0711-4fa0-81dc-add74c717457
		summarizeBy: none
		sourceColumn: Absence reason

		annotation SummarizationSetBy = Automatic

	column 'Duration 2020'
		dataType: int64
		formatString: 0
		lineageTag: 8bba0433-6a42-4cbc-913c-8188c3333017
		summarizeBy: sum
		sourceColumn: Duration 2020

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column 'unplanned duration'
		dataType: int64
		formatString: 0
		lineageTag: bf86a3f9-9783-4678-8b2b-0411191d31b0
		summarizeBy: sum
		sourceColumn: unplanned duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column 'planned duration'
		dataType: int64
		formatString: 0
		lineageTag: 4438bd89-8a10-4060-9b6b-7a2cdcbcc11c
		summarizeBy: sum
		sourceColumn: planned duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column 'Month calendar'
		dataType: string
		lineageTag: 8f72e5d1-212b-48c1-bea5-4fe1b7094db7
		summarizeBy: none
		sourceColumn: Month calendar
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Leave type Cat.'
		dataType: string
		lineageTag: bb01f716-5c83-4138-9c5c-26d7fde2135f
		summarizeBy: none
		sourceColumn: Leave type Cat.

		annotation SummarizationSetBy = Automatic

	column 'Year BF 2022'
		dataType: int64
		formatString: 0
		lineageTag: 2de930b8-9b5a-4745-a6a3-c9d0e3250f15
		summarizeBy: sum
		sourceColumn: Year BF 2022

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column 'Year BF 2023'
		dataType: int64
		formatString: 0
		lineageTag: 6a8fb074-9082-445a-b8ed-27ba6b0b5f8d
		summarizeBy: sum
		sourceColumn: Year BF 2023

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column 'Duration 2022'
		dataType: int64
		formatString: 0
		lineageTag: 2ea9ad3b-3357-4b63-9723-6419ad88caf3
		summarizeBy: sum
		sourceColumn: Duration 2022

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	column 'Duration 2023'
		dataType: int64
		formatString: 0
		lineageTag: 9546d332-c3ce-4c48-a7f9-3224b3b2e0a3
		summarizeBy: sum
		sourceColumn: Duration 2023

		annotation SummarizationSetBy = Automatic

		annotation PBI_ChangedProperties = ["DataType"]

	partition 'public employee_absences-388b070d-3665-49fa-83c6-1218a616ccd6' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("acwa-uaen-pdb01.postgres.database.azure.com", "data_centralized"),
				    public_employee_absences = Source{[Schema="public",Item="employee_absences"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(public_employee_absences, "Period", each if [start_date] >= #date(2021, 1, 1) then #date(2021, 1, 1) else if [start_date] >= #date(2021, 2, 1) then #date(2021, 2, 1) else if [start_date] >= #date(2021, 3, 1) then #date(2021, 3, 1) else if [start_date] >= #date(2021, 4, 1) then #date(2021, 4, 1) else if [start_date] >= #date(2021, 5, 1) then #date(2021, 5, 1) else if [start_date] >= #date(2021, 6, 1) then #date(2021, 6, 1) else if [start_date] >= #date(2021, 7, 1) then #date(2021, 7, 1) else if [start_date] >= #date(2021, 8, 1) then #date(2021, 8, 1) else if [start_date] >= #date(2021, 9, 1) then #date(2021, 9, 1) else if [start_date] >= #date(2021, 10, 1) then #date(2021, 10, 1) else if [start_date] >= #date(2021, 11, 1) then #date(2021, 11, 1) else if [start_date] >= #date(2021, 12, 1) then #date(2021, 12, 1) else 0),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Total Absence days", each if [start_date] <= [end_date] then [start_date] else if [end_date] = [start_date] - 1 then [start_date] else 0),
				    #"Filtered Rows" = Table.SelectRows(#"Added Conditional Column1", each true),
				    #"Added Conditional Column2" = Table.AddColumn(#"Filtered Rows", "TAD", each if [Total Absence days] <> #date(1999, 1, 30) then 1 else 0),
				    #"Added Conditional Column3" = Table.AddColumn(#"Added Conditional Column2", "Year BF", each if [Total Absence days] >= #date(2021, 1, 1) and [Total Absence days] <= #date(2022, 1, 1) then 2021 else if [Total Absence days] >= #date(2020, 1, 1) and [Total Absence days] <= #date(2021, 1, 1) then 2020 else if [Total Absence days] >= #date(2022, 1, 1) and [Total Absence days] <= #date(2023, 1, 1) then 2022 else if [Total Absence days] >= #date(2023, 1, 1) and [Total Absence days] <= #date(2024, 1, 1) then 2023 else 0),
				    #"Filtered Rows1" = Table.SelectRows(#"Added Conditional Column3", each true),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows1",{"TAD"}),
				    #"Added Conditional Column4" = Table.AddColumn(#"Removed Columns", "Year BF 2021", each if [Year BF] = 2021 and [planned] = "Unplanned" then 1 else 0),
				    #"Filtered Rows6" = Table.SelectRows(#"Added Conditional Column4", each true),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows6",{{"Year BF 2021", Int64.Type}}),
				    #"Added Conditional Column5" = Table.AddColumn(#"Changed Type", "Year BF 2020", each if [Year BF] = 2020 and [planned] = "Unplanned" then 1 else 0),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column5",{{"Year BF 2020", Int64.Type}}),
				    #"Added Conditional Column6" = Table.AddColumn(#"Changed Type1", "Duration 2021", each if [Year BF 2021] = 1 then [duration] else 0),
				    #"Filtered Rows5" = Table.SelectRows(#"Added Conditional Column6", each true),
				    #"Filtered Rows4" = Table.SelectRows(#"Filtered Rows5", each true),
				    #"Filtered Rows3" = Table.SelectRows(#"Filtered Rows4", each true),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows3", each true),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows2",{{"person_number", Order.Ascending}}),
				    #"Sorted Rows1" = Table.Sort(#"Sorted Rows",{{"status", Order.Ascending}, {"person_number", Order.Ascending}}),
				    #"Grouped Rows" = Table.Group(#"Sorted Rows1", {"person_number"}, {{"Count", each _, type table [status=nullable text, duration=nullable number, end_date=nullable date, start_date=nullable date, person_number=nullable text, absence_type=nullable text, reason=nullable text, absence_name=nullable text, balance=nullable text, planned=nullable text, ori=nullable text, Period=any, Total Absence days=date, Year BF=number, Year BF 2021=nullable number, Year BF 2020=nullable number, Duration 2021=number]}}),
				    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Custom", each Table.AddIndexColumn([Count],"Index",0)),
				    #"Expanded Custom" = Table.ExpandTableColumn(#"Added Custom", "Custom", {"status", "duration", "end_date", "start_date", "person_number", "absence_type", "reason", "absence_name", "balance", "planned", "ori", "Period", "Total Absence days", "Year BF", "Year BF 2021", "Year BF 2020", "Duration 2021", "Index"}, {"status", "duration", "end_date", "start_date", "person_number.1", "absence_type", "reason", "absence_name", "balance", "planned", "ori", "Period", "Total Absence days", "Year BF", "Year BF 2021", "Year BF 2020", "Duration 2021", "Index"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Expanded Custom", "Total Absence days", "Total Absence days - Copy"),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "Total Absence days - Copy", "Total Absence days - Copy - Copy"),
				    #"Removed Columns1" = Table.RemoveColumns(#"Duplicated Column1",{"Total Absence days - Copy", "Total Absence days - Copy - Copy"}),
				    #"Added Conditional Column7" = Table.AddColumn(#"Removed Columns1", "Planned", each if [planned] = "Planned" then 1 else 0),
				    #"Added Conditional Column8" = Table.AddColumn(#"Added Conditional Column7", "Unplanned", each if [planned] = "Unplanned" then 1 else 0),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Added Conditional Column8", "Total Absence days", "Total Absence days - Copy"),
				    #"Inserted Year" = Table.AddColumn(#"Duplicated Column2", "Year", each Date.Year([#"Total Absence days - Copy"]), Int64.Type),
				    #"Duplicated Column3" = Table.DuplicateColumn(#"Inserted Year", "Total Absence days - Copy", "Total Absence days - Copy - Copy"),
				    #"Inserted Month" = Table.AddColumn(#"Duplicated Column3", "Month", each Date.Month([#"Total Absence days - Copy - Copy"]), Int64.Type),
				    #"Added Conditional Column9" = Table.AddColumn(#"Inserted Month", "Leave p", each if [planned] = "Planned" then 1 else 0),
				    #"Added Conditional Column10" = Table.AddColumn(#"Added Conditional Column9", "Month name", each if [Month] = 1 then "Jan" else if [Month] = 2 then "Feb" else if [Month] = 3 then "Mar" else if [Month] = 4 then "Apr" else if [Month] = 5 then "May" else if [Month] = 6 then "Jun" else if [Month] = 7 then "Jul" else if [Month] = 8 then "Aug" else if [Month] = 9 then "Sep" else if [Month] = 10 then "Oct" else if [Month] = 11 then "Nov" else if [Month] = 12 then "Dec" else 0),
				    #"Added Conditional Column11" = Table.AddColumn(#"Added Conditional Column10", "Person count", each if [person_number] = [person_number] then 1 else 0),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column11",{{"Person count", Int64.Type}}),
				    #"Added Conditional Column12" = Table.AddColumn(#"Changed Type2", "Balance", each if [balance] = "Balance" then 1 else 0),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Conditional Column12",{{"Balance", Int64.Type}}),
				    #"Added Conditional Column13" = Table.AddColumn(#"Changed Type3", "Balance count", each if [balance] = "Count" then 1 else 0),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column13",{{"Balance", "Balance balance"}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns",{{"Balance count", Int64.Type}}),
				    #"Duplicated Column4" = Table.DuplicateColumn(#"Changed Type4", "planned", "planned - Copy"),
				    #"Added Conditional Column14" = Table.AddColumn(#"Duplicated Column4", "Planned number", each if [planned] = "Planned" then 1 else if [planned] = "Unplanned" then 1 else 0),
				    #"Added Conditional Column15" = Table.AddColumn(#"Added Conditional Column14", "Absence reason", each if [reason] = null then "None reason" else if [reason] = "Exposed/Self Isolating" then "Exposed/Self Isolating" else if [reason] = "Work from Home" then "Work from Home" else if [reason] = "Work From Home Country" then "Work From Home Country" else 0),
				    #"Added Conditional Column16" = Table.AddColumn(#"Added Conditional Column15", "Duration 2020", each if [Year BF 2020] = 1 then [duration] else 0),
				    #"Filtered Rows7" = Table.SelectRows(#"Added Conditional Column16", each true),
				    #"Added Conditional Column17" = Table.AddColumn(#"Filtered Rows7", "unplanned duration", each if [Unplanned] = 1 then [duration] else 0),
				    #"Added Conditional Column18" = Table.AddColumn(#"Added Conditional Column17", "planned duration", each if [Leave p] = 1 then [duration] else 0),
				    #"Filtered Rows8" = Table.SelectRows(#"Added Conditional Column18", each true),
				    #"Added Conditional Column19" = Table.AddColumn(#"Filtered Rows8", "Month calendar", each if [Month] = 1 then "Jan" else if [Month] = 2 then "Feb" else if [Month] = 3 then "Mar" else if [Month] = 4 then "Apr" else if [Month] = 5 then "May" else if [Month] = 6 then "Jun" else if [Month] = 7 then "Jul" else if [Month] = 8 then "Aug" else if [Month] = 9 then "Sep" else if [Month] = 10 then "Oct" else if [Month] = 11 then "Nov" else if [Month] = 12 then "Dec" else 0),
				    #"Added Conditional Column20" = Table.AddColumn(#"Added Conditional Column19", "Leave type Cat.", each if [absence_type] = "Working Day Annual Leave" then "Annual leave" else if [absence_type] = "Annual Leave EGY" then "Annual leave" else if [absence_type] = "Annual Leave Morocco" then "Annual leave" else if [absence_type] = "Annual Leave Morocco New" then "Annual leave" else if [absence_type] = "Annual Leave OMN" then "Annual leave" else if [absence_type] = "Annual Leave RPC_KSA" then "Annual leave" else if [absence_type] = "Annual Leave UAE" then "Annual leave" else if [absence_type] = "Annual Leave-BHR" then "Annual leave" else if [absence_type] = "Annual Leave-KSA" then "Annual leave" else if [absence_type] = "Annual Leave-MAR" then "Annual leave" else if [absence_type] = "Annual Leave-OMN" then "Annual leave" else if [absence_type] = "Annual Leave-UAE" then "Annual leave" else if [absence_type] = "Annual Leave-UAE_New" then "Annual leave" else if [absence_type] = "Annual Leave-ZAF" then "Annual leave"  else if [absence_type] = "Excess Annual Leave-OMN" then "Annual leave"  else if [absence_type] = "Annual Leave" then "Annual leave"  else if [absence_type] = "TUR_AnnualLeave" then "Annual leave" else if [absence_type] = "Vacation Leave-KSA" then "Annual leave" else if [absence_type] = "Compassionate Leave" then "Compassionate Leave" else if [absence_type] = "Bereavement Leave TUR" then "Compassionate Leave" else if [absence_type] = "Death Leave (Family)-KSA" then "Compassionate Leave" else if [absence_type] = "Bereavement Leave-UAE" then "Compassionate Leave" else if [absence_type] = "Death Leave (Family)-RPC_KSA" then "Compassionate Leave" else if [absence_type] = "Death Leave (Relatives)-KSA" then "Compassionate Leave" else if [absence_type] = "Death Leave EGY" then "Compassionate Leave" else if [absence_type] = "CDeath leave(Bereavement)-OMN" then "Death Leave_BHR" else if [absence_type] = "Death of a brother or sister & wife brother or sister" then "Compassionate Leave" else if [absence_type] = "Death of an ascendant, desendent & wife" then "Compassionate Leave" else if [absence_type] = "Paid-Special leave death-MAR" then "Compassionate Leave" else if [absence_type] = "Education Leave" then "Education Leave" else if [absence_type] = "Examination Leave(Study)-OMN" then "Education Leave" else if [absence_type] = "Examination Leave-KSA" then "Education Leave" else if [absence_type] = "Examination Leave-RPC_KSA" then "Education Leave" else if [absence_type] = "Examination Leave-UAE" then "Education Leave" else if [absence_type] = "Leave ½ Day-KSA" then "Education Leave" else if [absence_type] = "Leave for exam" then "Education Leave" else if [absence_type] = "Study Leave New-ZAF" then "Education Leave" else if [absence_type] = "Study leave-ZAF" then "Education Leave" else if [absence_type] = "Emergency Leave EGY" then "Emergency Leave" else if [absence_type] = "Emergency Leave-KSA" then "Emergency Leave" else if [absence_type] = "Emergency Leave-OMN" then "Emergency Leave" else if [absence_type] = "Emergency Leave-RPC_KSA" then "Emergency Leave" else if [absence_type] = "Hajj Leave" then "Hajj Leave" else if [absence_type] = "Hajj Leave-BHR" then "Hajj Leave" else if [absence_type] = "Hajj Leave-KSA" then "Hajj Leave" else if [absence_type] = "Hajj Leave-OMN" then "Hajj Leave" else if [absence_type] = "Hajj Leave-RPC_KSA" then "Hajj Leave" else if [absence_type] = "Hajj Leave-UAE" then "Hajj Leave" else if [absence_type] = "Marriage Leave" then "Marriage Leave" else if [absence_type] = "Marriage Leave TUR" then "Marriage Leave" else if [absence_type] = "Marriage Leave-BHR" then "Marriage Leave" else if [absence_type] = "Marriage Leave-KSA" then "Marriage Leave" else if [absence_type] = "Marriage leave-OMN" then "Marriage Leave" else if [absence_type] = "Marriage Leave-RPC_KSA" then "Marriage Leave" else if [absence_type] = "Marriage leave-UAE" then "Marriage Leave" else if [absence_type] = "Marriage of the child of the employee" then "Marriage Leave" else if [absence_type] = "Marriage of the Employee" then "Marriage Leave" else if [absence_type] = "Maternity Leave" then "Maternity Leave" else if [absence_type] = "Maternity Leave EGY" then "Maternity Leave"  else if [absence_type] = "Maternity Leave TUR" then "Maternity Leave" else if [absence_type] = "Maternity Leave Unpaid" then "Maternity Leave" else if [absence_type] = "Maternity Leave_BHR" then "Maternity Leave" else if [absence_type] = "Maternity Leave-OMN" then "Maternity Leave" else if [absence_type] = "Maternity Leave-UAE" then "Maternity Leave" else if [absence_type] = "Maternity Leave-ZAF" then "Maternity Leave" else if [absence_type] = "Unpaid - Maternity leave-MAR" then "Maternity Leave" else if [absence_type] = "Accompaniment of an ascendant for surgical operation" then "Other Paid Leave" else if [absence_type] = "Birth Leave RPC_KSA" then "Other Paid Leave" else if [absence_type] = "Birth of Child Leave_BHR" then "Other Paid Leave" else if [absence_type] = "Business Trip-KSA" then "Other Paid Leave" else if [absence_type] = "Circumcision" then "Other Paid Leave" else if [absence_type] = "Family Responsibility Leave-ZAF" then "Other Paid Leave" else if [absence_type] = "Leave for Seeking a New job TUR" then "Other Paid Leave" else if [absence_type] = "New Born" then "Other Paid Leave" else if [absence_type] = "Nursing Leave TUR" then "Other Paid Leave" else if [absence_type] = "Other Leave-ZAF" then "Other Paid Leave" else if [absence_type] = "Paid absence-OMN" then "Other Paid Leave" else if [absence_type] = "Paid absence-UAE" then "Other Paid Leave" else if [absence_type] = "Paid Compensation Leave-MAR" then "Other Paid Leave" else if [absence_type] = "Paid Substitution-MAR" then "Other Paid Leave" else if [absence_type] = "Paid-Birth-MAR" then "Other Paid Leave" else if [absence_type] = "Paid-Circumcision-MAR" then "Other Paid Leave" else if [absence_type] = "Paid-Excused absence-MAR" then "Other Paid Leave" else if [absence_type] = "Paid-Notice period-MAR" then "Other Paid Leave" else if [absence_type] = "Paid-Off days-MAR" then "Other Paid Leave" else if [absence_type] = "Paid-Wedding-MAR" then "Other Paid Leave" else if [absence_type] = "Sports Leave-ZAF" then "Other Paid Leave" else if [absence_type] = "Union Leave-ZAF" then "Other Paid Leave" else if [absence_type] = "EGY Absence Days" then "Other Unpaid Leave"  else if [absence_type] = "Iddah Leave-BHR" then "Other Unpaid Leave" else if [absence_type] = "EGY Penalty Days" then "Other Unpaid Leave"  else if [absence_type] = "Paternity Leave" then "Paternity Leave" else if [absence_type] = "Paternity Leave EGY" then "Paternity Leave" else if [absence_type] = "Paternity Leave TUR" then "Paternity Leave" else if [absence_type] = "Paternity leave-KSA" then "Paternity Leave" else if [absence_type] = "Paternity Leave-OMN" then "Paternity Leave" else if [absence_type] = "Paternity Leave-UAE" then "Paternity Leave" else if [absence_type] = "Unpaid Paternity Leave - ZAF" then "Paternity Leave" else if [absence_type] = "Sick Leave" then "Sick Leave" else if [absence_type] = "Paid - Sick leave-MAR" then "Sick Leave" else if [absence_type] = "Sick leave 100% KSA" then "Sick Leave" else if [absence_type] = "Sick Leave 100% Paid-KSA" then "Sick Leave" else if [absence_type] = "Sick leave 100% RPC_KSA" then "Sick Leave" else if [absence_type] = "Sick leave 75% KSA" then "Sick Leave" else if [absence_type] = "Sick Leave 75% Paid-KSA" then "Sick Leave" else if [absence_type] = "Sick leave 75% RPC_KSA" then "Sick Leave" else if [absence_type] = "Sick Leave EGY" then "Sick Leave" else if [absence_type] = "Sick leave For first 3 Month" then "Sick Leave" else if [absence_type] = "Sick leave from Month 4 to 6" then "Sick Leave" else if [absence_type] = "Sick leave from Month 7 until the end of the year" then "Sick Leave" else if [absence_type] = "Sick Leave Paid" then "Sick Leave" else if [absence_type] = "Sick Leave TUR" then "Sick Leave" else if [absence_type] = "Sick Leave Unpaid" then "Sick Leave" else if [absence_type] = "Sick Leave Unpaid Absence-RPC_KSA" then "Sick Leave" else if [absence_type] = "Sick leave unpaid-KSA" then "Sick Leave" else if [absence_type] = "Sick Leave_Half Paid-UAE" then "Sick Leave" else if [absence_type] = "Sick Leave_Paid-UAE" then "Sick Leave" else if [absence_type] = "Sick Leave_Unpaid-UAE" then "Sick Leave" else if [absence_type] = "Sick leave-100%Paid-OMN" then "Sick Leave" else if [absence_type] = "Sick leave-25%Paid-OMN" then "Sick Leave" else if [absence_type] = "Sick leave-50%Paid-OMN" then "Sick Leave" else if [absence_type] = "Sick leave-75%Paid-OMN" then "Sick Leave" else if [absence_type] = "Sick leave-UAE" then "Sick Leave" else if [absence_type] = "Sick Leave-ZAF" then "Sick Leave" else if [absence_type] = "SickLeave_Fullpaid-BHR" then "Sick Leave" else if [absence_type] = "SickLeave_Halfpaid-BHR" then "Sick Leave" else if [absence_type] = "SickLeave_UNpaid-BHR" then "Sick Leave" else if [absence_type] = "Unpaid - Sick leave-MAR" then "Sick Leave" else if [absence_type] = "BHR_TimeOff_InLieu" then "Time in Lieu" else if [absence_type] = "Comp Off" then "Time in Lieu" else if [absence_type] = "Comp Off BHR" then "Time in Lieu" else if [absence_type] = "Compensatory Off-OMN" then "Time in Lieu" else if [absence_type] = "Time-Off-in lieu" then "Time in Lieu" else if [absence_type] = "ZAF_TimeOff_InLieu" then "Time in Lieu" else if [absence_type] = "Unauthorised Leave-ZAF" then "Unauthorised Leave"  else if [absence_type] = "Unauthorized Absence-OMN" then "Unauthorised Leave"  else if [absence_type] = "Unauthorized Absence-UAE" then "Unauthorised Leave"  else if [absence_type] = "Unauthorized unpaid Leave-KSA" then "Unauthorised Leave" else if [absence_type] = "Authorized Unpaid Leave" then "Unpaid Leave" else if [absence_type] = "Authorized Unpaid Leave-KSA" then "Unpaid Leave" else if [absence_type] = "Unpaid Absence-KSA" then "Unpaid Leave" else if [absence_type] = "Unpaid absence-OMN" then "Unpaid Leave" else if [absence_type] = "Unpaid absence-UAE" then "Unpaid Leave" else if [absence_type] = "Unpaid Leave-BHR" then "Unpaid Leave" else if [absence_type] = "Unpaid Leave-UAE" then "Unpaid Leave" else if [absence_type] = "Unpaid Leave-ZAF" then "Unpaid Leave" else if [absence_type] = "Unpaid-Operation-MAR" then "Unpaid Leave" else if [absence_type] = "Unpaid-Suspension-MAR" then "Unpaid Leave" else if [absence_type] = "Unpaid-Unmotivated absence-MAR" then "Unpaid Leave" else if [absence_type] = "Working From Home" then "Work From Home" else if [absence_type] = "Paid-Work accident-MAR" then "Work Incident" else if [absence_type] = "Unpaid-Work accident-MAR" then "Work Incident" else 0),
				    #"Added Conditional Column21" = Table.AddColumn(#"Added Conditional Column20", "Year BF 2022", each if [Year BF] = 2022 and [planned] = "Unplanned" then 1 else 0),
				    #"Added Conditional Column22" = Table.AddColumn(#"Added Conditional Column21", "Year BF 2023", each if [Year BF] = 2023 and [planned] = "Unplanned" then 1 else 0),
				    #"Added Conditional Column23" = Table.AddColumn(#"Added Conditional Column22", "Duration 2022", each if [Year BF 2022] = 1 then [duration] else 0),
				    #"Added Conditional Column24" = Table.AddColumn(#"Added Conditional Column23", "Duration 2023", each if [Year BF 2023] = 1 then [duration] else 0),
				    #"Filtered Rows9" = Table.SelectRows(#"Added Conditional Column24", each true)
				in
				    #"Filtered Rows9"

	annotation PBI_ResultType = Table

