table PVM
	lineageTag: 5b80de47-7c7f-4786-8372-fb336635f0f2

	column PVM
		dataType: string
		lineageTag: 5ac5553e-0e05-4718-a386-53049882074b
		summarizeBy: none
		sourceColumn: PVM

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 23c65106-e991-4790-9912-258c66668e62
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column PVM_empty =
			
			if(PVM[PVM]="Joiners"," ","  ")
		lineageTag: 0d1faf96-e6f1-4a8d-bc8e-78d33c341a00
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition PVM = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8srPzEstKlbSUTJUitWJVvJJTSyD8I2UYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [PVM = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PVM", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

