table Table
	lineageTag: f0227ebb-a5a4-4b3c-8130-302e5cea447e

	column Slicer
		dataType: string
		lineageTag: c0d8ec0b-10f1-40cb-b3a9-306d468222af
		summarizeBy: none
		sourceColumn: Slicer
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: f5d68ee1-d8da-4b55-a81b-12470a06ec24
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcs4vzStR0lEyVIrViVZSBbKMlGJjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Slicer = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Slicer", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

