table 'Employee List Including Inactive'
	lineageTag: a8216a24-b73a-4859-a743-2c2bb64ce9b5

	measure '# of Joiner' = COUNTA('Employee List Including Inactive'[Date of Joining])
		formatString: 0
		lineageTag: 6305a418-3872-498a-af81-ae813ca45c9e

	measure 'Count of Leaver' =
			
			CALCULATE(
				COUNTA('Employee List Including Inactive'[Employee Status]),
				'Employee List Including Inactive'[Employee Status] IN { "Terminated" }
			)
		formatString: 0
		lineageTag: c2dcbfff-7875-417e-a33f-9850502f00d8

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "FilteredMeasure"
				}

		changedProperty = FormatString

	measure Attrition = [Total of leaver]/([HC by period]+[All HC by last period]/2)+0
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3050c756-b63e-43f0-85b9-a748ef65dcb8

	measure 'Count of Female Leaver' =
			
			CALCULATE(
				COUNTA('Employee List Including Inactive'[Employment Details Termination Date]),
				'Employee List Including Inactive'[Employee Status] IN { "Terminated" },
			    FILTER('Employee List Including Inactive','Employee List Including Inactive'[Gender] IN { "Female" }
			))
		formatString: 0
		lineageTag: 887c39f4-191d-4058-ad50-c0d360bf6f39

	measure 'Count of Female Joiner' =
			
			CALCULATE(
			    COUNTA('Employee List Including Inactive'[# of Joined employees]),
			FILTER ('Employee List Including Inactive','Employee List Including Inactive'[Gender] IN { "Female" }
			))
		formatString: 0
		lineageTag: cbeb46e5-4eca-485d-a39b-38d052b138b9

	measure 'Count of National Joiner' =
			
			CALCULATE(
			    COUNTA('Employee List Including Inactive'[Date of Joining]),
			FILTER('Employee List Including Inactive','Employee List Including Inactive'[National or Expat] IN {"National"}
			))
		formatString: 0
		lineageTag: fc73c57d-ce5c-4467-8bf1-83ee88be6484

	measure 'Count of National Leaver' =
			
			CALCULATE(
				COUNTA('Employee List Including Inactive'[Employment Details Termination Date]),
				'Employee List Including Inactive'[Employee Status] IN { "Terminated" },
			FILTER('Employee List Including Inactive','Employee List Including Inactive'[National or Expat] IN {"National"}
			))
		formatString: 0
		lineageTag: a9d68a3b-09aa-4bde-ad88-6dd3362d81d7

	measure 'Count of Saudi Leaver' =
			
			CALCULATE(
				COUNTA('Employee List Including Inactive'[Employment Details Termination Date]),
				'Employee List Including Inactive'[Employee Status] IN { "Terminated" },
			    'Employee List Including Inactive'[National or Expat] IN {"National"},
			FILTER('Employee List Including Inactive','Employee List Including Inactive'[Country/Region] IN {"Saudi Arabia"}
			))
		formatString: 0
		lineageTag: 29abc4ca-ac50-40c2-b04e-ce7b9e5bcfd3

	measure 'Count of Saudi Joiner' =
			
			CALCULATE(
			    COUNTA('Employee List Including Inactive'[Date of Joining]),
			            'Employee List Including Inactive'[National or Expat] IN {"National"},
			FILTER('Employee List Including Inactive','Employee List Including Inactive'[Country/Region] IN {"Saudi Arabia"}
			))
		formatString: 0
		lineageTag: 655669c1-2d41-4006-be97-79a1fd7fa511

	measure 'Total of leaver' = CALCULATE([Count of Leaver],USERELATIONSHIP('Employee List Including Inactive'[Employment Details Termination Date],'Calendar'[Date]))
		formatString: 0
		lineageTag: 4b7fc0a9-3c2d-49a0-8bed-435861e7641c

	measure 'Total of Female leaver' = CALCULATE([Count of Female Leaver],USERELATIONSHIP('Employee List Including Inactive'[Employment Details Termination Date],'Calendar'[Date]))
		formatString: 0
		lineageTag: 41d579eb-4cf3-4e9a-9b7e-1adb9c648777

	measure 'Saudi Expat HC by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			   COUNTA('Employee List Including Inactive'[National or Expat]),
			    'Employee List Including Inactive'[National or Expat] IN{"Expat"},
			    'Employee List Including Inactive'[Country/Region] IN{"Saudi Arabia"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			
			```
		formatString: #,0
		lineageTag: f261dd87-b79b-474a-a8cd-e598f2587252

	measure 'Total of National leaver' = CALCULATE([Count of National Leaver],USERELATIONSHIP('Employee List Including Inactive'[Employment Details Termination Date],'Calendar'[Date]))
		formatString: 0
		lineageTag: fd21f4a7-c090-4bc2-b179-582d8db9d153

	measure 'Total of Saudi leaver' = CALCULATE([Count of Saudi Leaver],USERELATIONSHIP('Employee List Including Inactive'[Employment Details Termination Date],'Calendar'[Date]))
		formatString: 0
		lineageTag: 60362ffc-db6e-4d3d-bdb8-edbc6d1fb939

	measure 'Target Saudization' = "81%"
		lineageTag: 7c21cfad-df39-4e33-8247-82778beb09a8

	measure 'Target Women' = "9%"
		lineageTag: 8bea7461-006b-4011-a824-8ac61981c5fc

	measure 'HC All' = COUNT('Employee List Including Inactive'[Person Id])
		formatString: 0
		lineageTag: a216a1f9-730f-4ca5-a149-f4473fcff5f8

	measure 'HC by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			    [HC All],
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			```
		formatString: #,0
		lineageTag: a7762859-b41e-480b-8bae-791f5bcc77da

	measure 'Locals by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			   COUNTA('Employee List Including Inactive'[National or Expat]),
			    'Employee List Including Inactive'[National or Expat] IN{"National"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			```
		formatString: #,0
		lineageTag: 5d798659-dc83-490f-a9d6-7755bcdebf8f

	measure 'HC in KSA by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			    COUNTA('Employee List Including Inactive'[Country/Region]),
			    'Employee List Including Inactive'[Country/Region] IN{"Saudi Arabia"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			```
		formatString: #,0
		lineageTag: 07773860-4ef4-46bc-b0be-792decb807c0

	measure 'Saudi HC by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			   COUNTA('Employee List Including Inactive'[National or Expat]),
			    'Employee List Including Inactive'[National or Expat] IN{"National"},
			    'Employee List Including Inactive'[Country/Region] IN{"Saudi Arabia"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			
			```
		formatString: #,0
		lineageTag: 3f2c64b7-9408-419a-8568-e3584c1648ad

	measure 'Women HC by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			   COUNTA('Employee List Including Inactive'[Gender]),
			    'Employee List Including Inactive'[Gender] IN{"Female"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			
			```
		formatString: #,0
		lineageTag: 854f9b90-00c1-4c23-873b-d266ca196cff

	measure 'All HC by last period' =
			
			CALCULATE(
			 [HC by period],
			PREVIOUSYEAR('Calendar'[Date].[Date]))
		formatString: 0
		lineageTag: af313b98-8fe8-49bc-8910-df94f6ca9464

	measure '% Saudi HC last period' = [Saudi (Prcentage) HC by period]/ [HC in KSA (Prcentage) by period]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 213b52ba-1342-4f0b-ae11-2fe54feba67a

	measure '% locals HC by Period' = [Locals (percentage) by period]/ [HC (Prcentage) by period]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 450eeb2b-6cdc-42a1-bfb8-6ca145215ad3

	measure '% Women HC by Period' = [Women (percentage) HC by period]/ [HC (Prcentage) by period]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 24a9e3cf-97d7-4022-a798-aa795f2fe884

	measure 'Average Age HC by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			     AVERAGEA('Employee List Including Inactive'[Age]),
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			```
		lineageTag: 69936c27-3e06-404d-818f-d6ef1b2cc985

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nationailites HC by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			    DISTINCTCOUNT('Employee List Including Inactive'[Nationality]),
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			```
		formatString: 0
		lineageTag: 4206ec46-dd27-49d3-b763-5b0f2a6a394a

	measure 'Expat by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			   COUNTA('Employee List Including Inactive'[National or Expat]),
			    'Employee List Including Inactive'[National or Expat] IN{"Expat"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			```
		formatString: #,0
		lineageTag: a3be06d4-2f4a-459a-95f5-de90f1aeb7e5

	measure '% Expats HC by Period' = [Expat by period]/ [HC by period]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: aa4b9b8e-2775-4cfc-8696-c71ea7c43960

	measure 'Male HC by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			   COUNTA('Employee List Including Inactive'[Gender]),
			    'Employee List Including Inactive'[Gender] IN{"Male"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			```
		formatString: #,0
		lineageTag: 3f45c164-baf8-4915-9951-ee49a3a9ed04

	measure 'Saudi (Prcentage) HC by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			   COUNTA('Employee List Including Inactive'[National or Expat]),
			    'Employee List Including Inactive'[National or Expat] IN{"National"},
			    'Employee List Including Inactive'[Country/Region] IN{"Saudi Arabia"},
			    'Employee List Including Inactive'[ET Saudi] IN{"In"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			```
		formatString: 0
		lineageTag: 5d782e27-eda5-43d9-a05f-3b3cd646163e

	measure 'HC in KSA (Prcentage) by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			    COUNTA('Employee List Including Inactive'[Country/Region]),
			    'Employee List Including Inactive'[Country/Region] IN{"Saudi Arabia"},
			'Employee List Including Inactive'[ET Saudi] IN{"In"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			```
		formatString: 0
		lineageTag: 91760c63-3a91-4c9f-a3aa-36985c0839ec

	measure 'Locals (percentage) by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			   COUNTA('Employee List Including Inactive'[National or Expat]),
			    'Employee List Including Inactive'[National or Expat] IN{"National"},
			'Employee List Including Inactive'[ET Saudi] IN{"In"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			```
		formatString: 0
		lineageTag: 842fde4f-438a-4b15-aedc-a0433aeb9090

	measure 'HC (Prcentage) by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			    [HC All],
			'Employee List Including Inactive'[ET Saudi] IN{"In"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			```
		formatString: 0
		lineageTag: 21a2f6a7-6c80-49d5-b98a-69869016c1ca

	measure 'Women (percentage) HC by period' = ```
			
			VAR EndDatePervisual= MAX('Calendar'[Date])
			VAR Result= 
			CALCULATE(
			   COUNTA('Employee List Including Inactive'[Gender]),
			    'Employee List Including Inactive'[Gender] IN{"Female"},
			'Employee List Including Inactive'[ET Saudi] IN{"In"},
			    REMOVEFILTERS('Calendar'),
			    'Employee List Including Inactive'[Date of Joining] <= EndDatePervisual,
			    'Employee List Including Inactive'[Employment Details Termination Date] > EndDatePervisual
			    ||
			    ISBLANK('Employee List Including Inactive'[Employment Details Termination Date])
			)
			RETURN
			Result
			
			```
		formatString: 0
		lineageTag: 55eae52e-8fde-4a2e-b4e9-fb93929d4292

	measure min_date_joining = MAX('Employee List Including Inactive'[Employment Details Termination Date])
		formatString: General Date
		lineageTag: a0cbd0b1-1819-4474-9765-3b91f13d3ffc

	column 'User/Employee ID'
		dataType: string
		lineageTag: c9b54c97-6a9a-457e-9f71-bcd33e8dc042
		summarizeBy: none
		sourceColumn: User/Employee ID

		annotation SummarizationSetBy = Automatic

	column 'Person Id'
		dataType: string
		lineageTag: 95adb382-b6d3-4093-9890-cafc811cac07
		summarizeBy: none
		sourceColumn: Person Id

		annotation SummarizationSetBy = Automatic

	column 'Date Of Birth'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d884f66-1260-4f9c-b254-b0cceb88e276
		summarizeBy: none
		sourceColumn: Date Of Birth

		variation Variation
			isDefault
			relationship: 5efba1a8-6a58-4daa-9ab5-f3f5bb136919
			defaultHierarchy: LocalDateTable_6465eed5-4bc2-42ab-a94c-99c8d4c9c71d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Gender
		dataType: string
		lineageTag: c3865635-bb4d-46f7-ae5d-8090b81ad8f2
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Nationality
		dataType: string
		lineageTag: ffa4b280-be27-458c-aa1c-0ee6c49a08bf
		summarizeBy: none
		sourceColumn: Nationality

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 0b6652c6-7167-48af-8b45-ac9eef177bf3
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Employee Status'
		dataType: string
		lineageTag: 34d8a6a3-a83b-4749-a966-2cfb6c88acd4
		summarizeBy: none
		sourceColumn: Employee Status

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: a267272a-b2f9-409b-baf7-00818c9146e0
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column 'Employment Type'
		dataType: string
		lineageTag: 7fc4f4cc-1409-4cc8-8bf1-6b21af7afe09
		summarizeBy: none
		sourceColumn: Employment Type

		annotation SummarizationSetBy = Automatic

	column 'Employment Details Hire Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 07ff90f8-9704-4a01-88ae-349c8ba0d674
		summarizeBy: none
		sourceColumn: Employment Details Hire Date

		variation Variation
			isDefault
			relationship: f914b183-88ec-4311-b89f-58c55dac7f7a
			defaultHierarchy: LocalDateTable_8622c2a1-f3ab-4c45-98d5-c6386b6a3298.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Employment Details Group Joining Date'
		dataType: dateTime
		formatString: d mmmm\, yyyy
		lineageTag: 48261cf0-d389-4c1c-8705-f494f3df9368
		summarizeBy: none
		sourceColumn: Employment Details Group Joining Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Employment Details Employer Name'
		dataType: string
		lineageTag: 9d5979a1-1d93-4d0a-9f2c-e3c75ed80719
		summarizeBy: none
		sourceColumn: Employment Details Employer Name

		annotation SummarizationSetBy = Automatic

	column 'Employment Details Termination Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9737f2b1-d1c0-40a0-b099-464d7cd2690a
		summarizeBy: none
		sourceColumn: Employment Details Termination Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Employment Details Contract End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e69ab044-14b6-4d86-a520-021a6afbb1dd
		summarizeBy: none
		sourceColumn: Employment Details Contract End Date

		variation Variation
			isDefault
			relationship: e0809039-1f27-45fa-8c16-96448e4eb748
			defaultHierarchy: LocalDateTable_4fd2075d-c7d0-4840-83d3-60f3054d1440.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Event Reason'
		dataType: string
		lineageTag: c197bb1f-2b97-44fa-a571-6a107d3490b7
		summarizeBy: none
		sourceColumn: Event Reason

		annotation SummarizationSetBy = Automatic

	column 'Probationary Period End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bd47eb97-61d9-4cf5-bf60-bbca8487fd49
		summarizeBy: none
		sourceColumn: Probationary Period End Date

		variation Variation
			isDefault
			relationship: 205f407e-aff5-4ef8-bd4b-cd354967d829
			defaultHierarchy: LocalDateTable_9c6fca44-8e21-4c51-8cc1-0eb979ccd261.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Position Entry Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 157a9f62-6230-4e86-bae8-c2f6a8b4003a
		summarizeBy: none
		sourceColumn: Position Entry Date

		variation Variation
			isDefault
			relationship: da43da9d-7a0e-415e-9f99-03e4e58cc9ff
			defaultHierarchy: LocalDateTable_5f8ab98f-4e95-4959-b20a-8ccdd57d9092.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'GEO Name'
		dataType: string
		lineageTag: e40580ad-aed4-4b8c-8a9d-1675b5a5b8c0
		summarizeBy: none
		sourceColumn: GEO Name

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 51f47668-7c47-43ae-890e-f3a73ba95ab8
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Age group' =
			
			IF('Employee List Including Inactive'[Age] <30,"18-30",
			IF('Employee List Including Inactive'[Age]<40, "30-40",
			IF('Employee List Including Inactive'[Age] <50,"40-50",
			IF('Employee List Including Inactive'[Age] <60,"50-60",
			IF('Employee List Including Inactive'[Age] >60, "60+")))))
		lineageTag: 978ff004-4e15-4f02-861d-c11fae0cc41b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Remining Trminated month' = DATEDIFF('Employee List Including Inactive'[Date of Joining].[Date],'Employee List Including Inactive'[Employment Details Termination Date], MONTH)
		formatString: 0
		lineageTag: 7b8099b1-acfa-466d-be90-926a6ec8086a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Lenghth group' =
			
			IF(ISBLANK('Employee List Including Inactive'[Remining Trminated month]),BLANK(),
			IF('Employee List Including Inactive'[Remining Trminated month]<6,"Less than 6 Months",
			IF('Employee List Including Inactive'[Remining Trminated month] <=12, "6-12 months",
			IF('Employee List Including Inactive'[Remining Trminated month] <=36,"1-3 Years",
			IF('Employee List Including Inactive'[Remining Trminated month] <=60,"3-5 Years",
			IF('Employee List Including Inactive'[Remining Trminated month] >60, "more than 5 years"
			))))))
		lineageTag: d9286471-f0e4-47a5-8adf-eee81a722e04
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Saudi & NonSaudi 11' = ```
			
			IF('Employee List Including Inactive'[Nationality]= "Saudi Arabian" &&
			   'Employee List Including Inactive'[Country/Region]= "Saudi Arabia", 
			   "Saudi","non Saudi")
			```
		lineageTag: 97fb3882-c3bb-4b04-8b51-9bbd9e159e27
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Termintion out_in' = ```
			
			IF('Employee List Including Inactive'[Event Reason]="74-Relocation / Work Location" ||
			   'Employee List Including Inactive'[Event Reason]= "42-Transfer to Subsidiary" ||
			    'Employee List Including Inactive'[Event Reason]= "94-Transfer to 3rd Party" ||
			    'Employee List Including Inactive'[Event Reason]= "14-Mis - Conduct" ||
			    'Employee List Including Inactive'[Event Reason]= "3-Data Change" ||
			    'Employee List Including Inactive'[Event Reason]= "GLREC-Go Live Record" ||
			    'Employee List Including Inactive'[Event Reason]= "5-Change in Payroll Area" ||
			    'Employee List Including Inactive'[Event Reason]= "50-Company code change" ||
			    'Employee List Including Inactive'[Event Reason]= "99-Data Conversion", 
			    "IN","Out")
			```
		lineageTag: 3eca76da-b134-48e0-9684-74fc0bda094c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Termintion out_in 1' = ```
			
			IF('Employee List Including Inactive'[Event Reason]=" 116-Mutual Agreement" ||
			   'Employee List Including Inactive'[Event Reason]= "40-End of Contract /Restructuring" ||
			    'Employee List Including Inactive'[Event Reason]= "2-Resignation" ||
			    'Employee List Including Inactive'[Event Reason]= "73-Continue Education" ||
			    'Employee List Including Inactive'[Event Reason]= "32-New Job / Better Opportunity" ||
			    'Employee List Including Inactive'[Event Reason]= "110-Dissatisfied with Work/Location" ||
			    'Employee List Including Inactive'[Event Reason]= "113-Disciplinary Outcome" ||
			    'Employee List Including Inactive'[Event Reason]= "80-Family / Personal" ||
			    'Employee List Including Inactive'[Event Reason]= "112-Absconded"||
			    'Employee List Including Inactive'[Event Reason]= "82-During Probation"||
			    'Employee List Including Inactive'[Event Reason]= "15-Restructuring"||
			    'Employee List Including Inactive'[Event Reason]= "13-Poor Performance"|| 
			    'Employee List Including Inactive'[Event Reason]= "69-Fail to pass Probation Period"|| 
			    'Employee List Including Inactive'[Event Reason]= "72-Personal Reason"|| 
			    'Employee List Including Inactive'[Event Reason]= "75-Dissatisfied: Work/Management"|| 
			    'Employee List Including Inactive'[Event Reason]= "37-Company Violation"|| 
			    'Employee List Including Inactive'[Event Reason]= "112-Absconded"||
			    'Employee List Including Inactive'[Event Reason]= "43-Death"||
			    'Employee List Including Inactive'[Event Reason]= "38-Low Performance"||
			    'Employee List Including Inactive'[Event Reason]= "39-Age / Retirement"||
			    'Employee List Including Inactive'[Event Reason]= "67-Medical Grounds"||
			    'Employee List Including Inactive'[Event Reason]= "66-3 months of Probation"|| 
			    'Employee List Including Inactive'[Event Reason]= "41-Localization Program"|| 
			    'Employee List Including Inactive'[Event Reason]= "03-Vacant"|| 
			    'Employee List Including Inactive'[Event Reason]= "52-Personnel subarea change",
			    "Out","IN")
			
			```
		lineageTag: 2e9987d0-b69a-4ab7-aa57-fd25cb8a1a77
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Date of Joining'
		dataType: dateTime
		formatString: d mmmm\, yyyy
		lineageTag: b2d898f1-74b9-4790-a278-816132dfccf9
		summarizeBy: none
		sourceColumn: Date of Joining

		variation Variation
			isDefault
			relationship: 38556614-e8ed-47b8-bc96-19f74466db90
			defaultHierarchy: LocalDateTable_73ab7b3f-18d3-4c9d-96eb-8cabd1ac0c29.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column '# of Joined employees'
		dataType: int64
		formatString: 0
		lineageTag: 126121c8-6080-4326-aa80-5dcd03bf9307
		summarizeBy: sum
		sourceColumn: # of Joined employees

		annotation SummarizationSetBy = Automatic

	column 'Employment Type - Copy'
		dataType: string
		lineageTag: ae4cc2dd-a3e0-4a74-857d-9d140646fad5
		summarizeBy: none
		sourceColumn: Employment Type - Copy

		annotation SummarizationSetBy = Automatic

	column 'ET Saudi'
		dataType: string
		lineageTag: 21071785-0ccc-4e0a-b9cd-f54632296b03
		summarizeBy: none
		sourceColumn: ET Saudi

		annotation SummarizationSetBy = Automatic

	column 'National or Expat' =
			
			IF('Employee List Including Inactive'[Country/Region]="Morocco" && 'Employee List Including Inactive'[Nationality]= "Moroccan"||
			'Employee List Including Inactive'[Country/Region]="Bahrain" && 'Employee List Including Inactive'[Nationality]= "Bahraini"||
			 'Employee List Including Inactive'[Country/Region]="Saudi Arabia" && 'Employee List Including Inactive'[Nationality]= "Saudi Arabian"||
			 'Employee List Including Inactive'[Country/Region]="United Arab Emirates" && 'Employee List Including Inactive'[Nationality]= "Emirati"||
			 'Employee List Including Inactive'[Country/Region]="China" && 'Employee List Including Inactive'[Nationality]= "Chinese"||
			 'Employee List Including Inactive'[Country/Region]="Egypt" && 'Employee List Including Inactive'[Nationality]= "Egyptian"||
			 'Employee List Including Inactive'[Country/Region]="Indonesia" && 'Employee List Including Inactive'[Nationality]= "Indonesian"||
			 'Employee List Including Inactive'[Country/Region]="Jordan" && 'Employee List Including Inactive'[Nationality]= "Jordanian"||
			 'Employee List Including Inactive'[Country/Region]="Oman" && 'Employee List Including Inactive'[Nationality]= "Omani"||
			 'Employee List Including Inactive'[Country/Region]="South Africa" && 'Employee List Including Inactive'[Nationality]= "South African"||
			 'Employee List Including Inactive'[Country/Region]="Turkey" && 'Employee List Including Inactive'[Nationality]= "Turkish"||
			  'Employee List Including Inactive'[Country/Region]="Uzbekistan" && 'Employee List Including Inactive'[Nationality]= "Uzbekistani"||
			  'Employee List Including Inactive'[Country/Region]="Vietnam" && 'Employee List Including Inactive'[Nationality]= "Vietnamese",
			"National","Expat")
		lineageTag: 9d734958-c94d-4b59-bff0-856de1adba66
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Pay Grade Name'
		dataType: string
		lineageTag: 3d755559-2bff-4a32-80c9-90e39ee09075
		summarizeBy: none
		sourceColumn: Pay Grade Name

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Employee List Including Inactive","TableItemName":"Pay Grade Name (groups)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'User/Employee Name'
		dataType: string
		lineageTag: 27404fd9-a38a-4337-8f04-da1d8e26f1e6
		summarizeBy: none
		sourceColumn: User/Employee Name

		annotation SummarizationSetBy = Automatic

	column 'Pay Grade Name (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('Employee List Including Inactive'[Pay Grade Name]),
				"(Blank)",
				'Employee List Including Inactive'[Pay Grade Name] IN {"01",
					"03",
					"05",
					"06",
					"08",
					"09",
					"10",
					"11",
					"12",
					"13",
					"14",
					"15",
					"16",
					"17",
					"18",
					"19",
					"20",
					"21",
					"22",
					"23",
					"L10",
					"L11",
					"L12",
					"L13",
					"L14",
					"L15",
					"L17",
					"L3",
					"L4",
					"L5",
					"L6",
					"L7",
					"L8",
					"L9"},
				"Associates.",
				'Employee List Including Inactive'[Pay Grade Name] IN {"M1",
					"M2",
					"M3"},
				"Middle Mgt.",
				'Employee List Including Inactive'[Pay Grade Name] IN {"E1",
					"E2",
					"E3",
					"E4",
					"E5",
					"E6"},
				"Senior Mgt.",
				'Employee List Including Inactive'[Pay Grade Name]
			)
		isHidden
		lineageTag: d6c6a7b2-d24f-4744-aef1-59c981acdf16
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Employee List Including Inactive"
				          }
				        },
				        "Property": "Pay Grade Name"
				      }
				    }
				  ]
				}

		changedProperty = IsHidden

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"e","Entity":"Employee List Including Inactive"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"Pay Grade Name"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"Associates.","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"Pay Grade Name"}}],"Values":[[{"Literal":{"Value":"'01'"}}],[{"Literal":{"Value":"'03'"}}],[{"Literal":{"Value":"'05'"}}],[{"Literal":{"Value":"'06'"}}],[{"Literal":{"Value":"'08'"}}],[{"Literal":{"Value":"'09'"}}],[{"Literal":{"Value":"'10'"}}],[{"Literal":{"Value":"'11'"}}],[{"Literal":{"Value":"'12'"}}],[{"Literal":{"Value":"'13'"}}],[{"Literal":{"Value":"'14'"}}],[{"Literal":{"Value":"'15'"}}],[{"Literal":{"Value":"'16'"}}],[{"Literal":{"Value":"'17'"}}],[{"Literal":{"Value":"'18'"}}],[{"Literal":{"Value":"'19'"}}],[{"Literal":{"Value":"'20'"}}],[{"Literal":{"Value":"'21'"}}],[{"Literal":{"Value":"'22'"}}],[{"Literal":{"Value":"'23'"}}],[{"Literal":{"Value":"'L10'"}}],[{"Literal":{"Value":"'L11'"}}],[{"Literal":{"Value":"'L12'"}}],[{"Literal":{"Value":"'L13'"}}],[{"Literal":{"Value":"'L14'"}}],[{"Literal":{"Value":"'L15'"}}],[{"Literal":{"Value":"'L17'"}}],[{"Literal":{"Value":"'L3'"}}],[{"Literal":{"Value":"'L4'"}}],[{"Literal":{"Value":"'L5'"}}],[{"Literal":{"Value":"'L6'"}}],[{"Literal":{"Value":"'L7'"}}],[{"Literal":{"Value":"'L8'"}}],[{"Literal":{"Value":"'L9'"}}]]}}},{"DisplayName":"Middle Mgt.","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"Pay Grade Name"}}],"Values":[[{"Literal":{"Value":"'M1'"}}],[{"Literal":{"Value":"'M2'"}}],[{"Literal":{"Value":"'M3'"}}]]}}},{"DisplayName":"Senior Mgt.","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"Pay Grade Name"}}],"Values":[[{"Literal":{"Value":"'E1'"}}],[{"Literal":{"Value":"'E2'"}}],[{"Literal":{"Value":"'E3'"}}],[{"Literal":{"Value":"'E4'"}}],[{"Literal":{"Value":"'E5'"}}],[{"Literal":{"Value":"'E6'"}}]]}}}]}

		annotation SummarizationSetBy = Automatic

	partition 'Employee List Including Inactive' = m
		mode: import
		source = ```
				let
				    Source = PostgreSQL.Database("acwa-prod-psdb-acwadp.postgres.database.azure.com", "postgres"),
				    #"Employee List including Inactiv_Sheet" = Source{[Schema="gdm",Item="f_employee_pc"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Employee List including Inactiv_Sheet",{
				{"Person Id", type text},
				{"Date Of Birth", Int64.Type},
				{"Nationality", type text}, 
				{"Name", type text},  
				{"Employee Status", type text}, 
				{"Country/Region", type text}, 
				{"Employment Type", type text}, 
				{"Employment Details Hire Date", Int64.Type}, 
				{"Employment Details Group Joining Date", Int64.Type}, 
				{"Employment Details Employer Name", type text}, 
				{"Employment Details Termination Date", Int64.Type}, 
				{"Pay Grade Name", type text},
				{"Event Reason", type text},
				{"User/Employee ID", Int64.Type},
				{"User/Employee Name", type text},
				{"Probationary Period End Date", Int64.Type},
				{"Position Entry Date", Int64.Type},
				{"Gender", type text},
				{"Employment Details Contract End Date", Int64.Type},
				{"GEO Name", type text}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Changed Type", {{"Date Of Birth", type date}}, "ar-KW"),
				    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Changed Type with Locale", {{"Employment Details Hire Date", type date}}, "ar-KW"),
				    #"Changed Type with Locale2" = Table.TransformColumnTypes(#"Changed Type with Locale1", {{"Employment Details Group Joining Date", type date}}, "ar-KW"),
				    #"Changed Type with Locale3" = Table.TransformColumnTypes(#"Changed Type with Locale2", {{"Employment Details Termination Date", type date}}, "ar-KW"),
				    #"Changed Type with Locale4" = Table.TransformColumnTypes(#"Changed Type with Locale3", {{"Employment Details Contract End Date", type date}}, "ar-KW"),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type with Locale4", "Date Of Birth", "Date Of Birth - Copy"),
				    #"Calculated Age" = Table.TransformColumns(#"Duplicated Column",{{"Date Of Birth - Copy", each Date.From(DateTime.LocalNow()) - _, type duration}}),
				    #"Calculated Total Years" = Table.TransformColumns(#"Calculated Age",{{"Date Of Birth - Copy", each Duration.TotalDays(_) / 365, type number}}),
				    #"Rounded Down" = Table.TransformColumns(#"Calculated Total Years",{{"Date Of Birth - Copy", Number.RoundDown, Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Rounded Down",{{"Date Of Birth - Copy", "Age"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","Inactive","Terminated",Replacer.ReplaceText,{"Employee Status"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value",{{"User/Employee ID", type text}}),
				    #"Changed Type with Locale7" = Table.TransformColumnTypes(#"Changed Type4", {{"Position Entry Date", type date}}, "ar-KW"),
				    #"Changed Type with Locale8" = Table.TransformColumnTypes(#"Changed Type with Locale7", {{"Probationary Period End Date", type date}}, "ar-KW"),
				    #"Filtered Rows2" = Table.SelectRows(#"Changed Type with Locale8", each true),
				    #"Added Conditional Column3" = Table.AddColumn(#"Filtered Rows2", "Date of Joining ", each if [Employment Details Group Joining Date] = null then [Employment Details Hire Date] else [Employment Details Group Joining Date]),
				    #"Changed Type with Locale11" = Table.TransformColumnTypes(#"Added Conditional Column3", {{"Date of Joining ", type date}}, "ar-KW"),
				    #"Added Conditional Column4" = Table.AddColumn(#"Changed Type with Locale11", "# of Joined employees", each if [#"Date of Joining "] = [#"Date of Joining "] then 1 else 0),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column4",{{"# of Joined employees", Int64.Type}}),
				    #"Duplicated Column6" = Table.DuplicateColumn(#"Changed Type2", "Employment Type", "Employment Type - Copy"),
				    #"Added Conditional Column10" = Table.AddColumn(#"Duplicated Column6", "ET Saudi", each if [Employment Type] = "Contingent Worker" then "Out" else if [Employment Type] = "Third Party Employee" then "Out" else if [Employment Type] = "Company Consultant" then "Out" else "In"),
				    #"Filtered Rows5" = Table.SelectRows(#"Added Conditional Column10", each true),
				    #"Filtered Rows4" = Table.SelectRows(#"Filtered Rows5", each true),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Filtered Rows4",{{"User/Employee ID", type text}}),
				    #"Sorted Rows" = Table.Buffer (Table.Sort(#"Changed Type5",{{"Employment Details Hire Date", Order.Descending}})),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"Person Id"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each ([Employee Status] <> null)),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each ([Employment Type] <> null and [Employment Type] <> "Contingent Worker" and [Employment Type] <> "Company Consultant") and ([Employment Details Employer Name] <> "MEETHAQ Employment Agency" and [Employment Details Employer Name] <> "Other Consultancy Agreement")),
				    #"Changed Type with Locale12" = Table.TransformColumnTypes(#"Filtered Rows1", {{"Employment Details Termination Date", type date}}, "ar-KW"),
				    #"Rinominate colonne" = Table.RenameColumns(#"Changed Type with Locale12",{{"Date of Joining ", "Date of Joining"}})
				in
				    #"Rinominate colonne"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

