table ghe_Gift_Declaration_Logs
	lineageTag: 2e3388cb-4e19-4d1b-b4a6-f3dbcbfd4572

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 5
		incrementalGranularity: day
		incrementalPeriods: 2
		sourceExpression =
			let
			    Source = SharePoint.Tables("https://acwapi.sharepoint.com/sites/ComplianceSolution-PROD", [Implementation=null, ApiVersion=15]),
			    #"d53deb83-09c7-4500-869f-b721defabd08" = Source{[Id="d53deb83-09c7-4500-869f-b721defabd08"]}[Items],
			    #"Removed Columns" = Table.RemoveColumns(#"d53deb83-09c7-4500-869f-b721defabd08",{"FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Gift_Declaration_Lookup", "Declaration_LC_SubStatus_Lookup", "ct_RoleLookup", "Author", "Editor"}),
			    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each [Time_Stamp] <= RangeEnd and [Time_Stamp] >= RangeStart),
			    #"Renamed Columns1" = Table.RenameColumns(#"Filtered Rows",{{"ID", "ID.1"}}),
			    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Time_Stamp", type datetime}}),
			    #"Expanded Declaration_LC_Status_Lookup" = Table.ExpandRecordColumn(#"Changed Type", "Declaration_LC_Status_Lookup", {"Name", "Display_Name"}, {"Declaration_LC_Status_Lookup.Name", "Declaration_LC_Status_Lookup.Display_Name"})
			in
			    #"Expanded Declaration_LC_Status_Lookup"

	column FileSystemObjectType
		dataType: string
		lineageTag: f575436e-75b0-4cda-aa2b-c54143bad2b1
		summarizeBy: none
		sourceColumn: FileSystemObjectType

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 85c4f5f2-c7fc-47e0-a50a-c13126bcbcc5
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUri
		dataType: string
		lineageTag: 036a5073-5712-4a90-aa15-e6aefbf54596
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUri

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUrl
		dataType: string
		lineageTag: 0890c6ff-6627-4450-aaad-caa44a42434a
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUrl

		annotation SummarizationSetBy = Automatic

	column 'ID.1'
		dataType: string
		lineageTag: 14647bcd-5d18-4239-8c3c-651d872a5af4
		summarizeBy: none
		sourceColumn: ID.1

		annotation SummarizationSetBy = Automatic

	column ContentTypeId
		dataType: string
		lineageTag: 63b0677e-f02d-4d36-9220-3e9e873cbfd5
		summarizeBy: none
		sourceColumn: ContentTypeId

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: c2197c44-69f0-4f75-942b-90ac0f7c61a3
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: string
		lineageTag: 08c2855c-b85d-4c68-989b-13da62421bed
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: string
		lineageTag: 1faf5bcc-9370-48d1-a3f5-276a9701492f
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: string
		lineageTag: 7d558c6d-5d5f-48bd-81b7-122914c2676d
		summarizeBy: none
		sourceColumn: AuthorId

		annotation SummarizationSetBy = Automatic

	column EditorId
		dataType: string
		lineageTag: a0af8842-d055-4c72-a7ca-b4e8978b09b6
		summarizeBy: none
		sourceColumn: EditorId

		annotation SummarizationSetBy = Automatic

	column OData__UIVersionString
		dataType: string
		lineageTag: 3813f83d-2458-4b39-b07c-7866a23017aa
		summarizeBy: none
		sourceColumn: OData__UIVersionString

		annotation SummarizationSetBy = Automatic

	column Attachments
		dataType: string
		lineageTag: ac9ac145-cbf7-412e-b2f2-a58bddf0cd58
		summarizeBy: none
		sourceColumn: Attachments

		annotation SummarizationSetBy = Automatic

	column GUID
		dataType: string
		lineageTag: 7c9cca57-5c7a-42f4-9789-0d3608c30b73
		summarizeBy: none
		sourceColumn: GUID

		annotation SummarizationSetBy = Automatic

	column ComplianceAssetId
		dataType: string
		lineageTag: 63ad711b-9cb1-477f-ad3c-25f651760138
		summarizeBy: none
		sourceColumn: ComplianceAssetId

		annotation SummarizationSetBy = Automatic

	column Gift_Declaration_LookupId
		dataType: string
		lineageTag: 8e248308-0d62-4997-9780-1d24d58d4897
		summarizeBy: none
		sourceColumn: Gift_Declaration_LookupId

		annotation SummarizationSetBy = Automatic

	column Time_Stamp
		dataType: dateTime
		formatString: General Date
		lineageTag: ca5e2f06-ec78-45e0-b13d-46da9fd6a414
		summarizeBy: none
		sourceColumn: Time_Stamp

		variation Variation
			isDefault
			relationship: 93bcfa34-8108-4fb3-89cb-7440ef33cc85
			defaultHierarchy: LocalDateTable_3a864fd1-5794-4e6a-848f-a166bfd453ff.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Declaration_LC_Status_LookupId
		dataType: string
		lineageTag: acc983bb-9c10-4a88-af47-da6aa1c691fd
		summarizeBy: none
		sourceColumn: Declaration_LC_Status_LookupId

		annotation SummarizationSetBy = Automatic

	column Declaration_LC_SubStatus_LookupId
		dataType: string
		lineageTag: ef74624e-e296-402d-9dfa-e53ed2176f6d
		summarizeBy: none
		sourceColumn: Declaration_LC_SubStatus_LookupId

		annotation SummarizationSetBy = Automatic

	column ct_Comments
		dataType: string
		lineageTag: d38a053c-8be0-4ad3-9354-ed3800abbfc4
		summarizeBy: none
		sourceColumn: ct_Comments

		annotation SummarizationSetBy = Automatic

	column ct_RoleLookupId
		dataType: string
		lineageTag: f0a082e1-f840-411f-98de-00e6917abc0c
		summarizeBy: none
		sourceColumn: ct_RoleLookupId

		annotation SummarizationSetBy = Automatic

	column OData__ColorTag
		dataType: string
		lineageTag: f3720475-f857-439f-9faf-15795cb169ff
		summarizeBy: none
		sourceColumn: OData__ColorTag

		annotation SummarizationSetBy = Automatic

	column 'Declaration_LC_Status_Lookup.Name'
		dataType: string
		lineageTag: 96ff6f08-0e84-4bb4-97bb-61d27b8d66ad
		summarizeBy: none
		sourceColumn: Declaration_LC_Status_Lookup.Name

		annotation SummarizationSetBy = Automatic

	column 'Declaration_LC_Status_Lookup.Display_Name'
		dataType: string
		lineageTag: 97af7181-b8ba-40d8-9607-8aa645207176
		summarizeBy: none
		sourceColumn: Declaration_LC_Status_Lookup.Display_Name

		annotation SummarizationSetBy = Automatic

	column Initiated_Date = CALCULATE(selectedvalue(ghe_Gift_Declaration_Logs[Time_Stamp]),ALLEXCEPT(ghe_Gift_Declaration_Logs,ghe_Gift_Declaration_Logs[Gift_Declaration_LookupId]),ghe_Gift_Declaration_Logs[Declaration_LC_Status_Lookup.Name]="Draft")
		formatString: General Date
		lineageTag: 54f9a722-dc6e-4fac-a003-a56e49a3a272
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 5b32e529-b7c9-490f-9f1d-d59abe03d16e
			defaultHierarchy: LocalDateTable_a6f1b0e7-3c3a-4809-abb9-182d75a28afc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Status Date' = CALCULATE(MAX(ghe_Gift_Declaration_Logs[Time_Stamp]),ALLEXCEPT(ghe_Gift_Declaration_Logs,ghe_Gift_Declaration_Logs[Gift_Declaration_LookupId]))
		formatString: General Date
		lineageTag: 8d559bf4-c6c3-4521-9a29-2aac6cc373ca
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 646f0d9a-3bca-47cf-bdf0-f4297d1200ff
			defaultHierarchy: LocalDateTable_0e50ba9f-e3da-4cf0-89bc-b0e3fafae499.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition ghe_Gift_Declaration_Logs = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://acwapi.sharepoint.com/sites/ComplianceSolution-PROD", [Implementation=null, ApiVersion=15]),
				    #"d53deb83-09c7-4500-869f-b721defabd08" = Source{[Id="d53deb83-09c7-4500-869f-b721defabd08"]}[Items],
				    #"Removed Columns" = Table.RemoveColumns(#"d53deb83-09c7-4500-869f-b721defabd08",{"FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Gift_Declaration_Lookup", "Declaration_LC_SubStatus_Lookup", "ct_RoleLookup", "Author", "Editor"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each [Time_Stamp] <= RangeEnd and [Time_Stamp] >= RangeStart),
				    #"Renamed Columns1" = Table.RenameColumns(#"Filtered Rows",{{"ID", "ID.1"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Time_Stamp", type datetime}}),
				    #"Expanded Declaration_LC_Status_Lookup" = Table.ExpandRecordColumn(#"Changed Type", "Declaration_LC_Status_Lookup", {"Name", "Display_Name"}, {"Declaration_LC_Status_Lookup.Name", "Declaration_LC_Status_Lookup.Display_Name"})
				in
				    #"Expanded Declaration_LC_Status_Lookup"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

