table 'A08 - Reporting Scheduled Start Date'
	lineageTag: 0a731db8-9fe4-48cb-a2fb-c91c20e6b3b9

	column ProjectPhaseId
		dataType: int64
		formatString: 0
		lineageTag: 407df4ac-9af3-4300-832f-e3519fe54bec
		summarizeBy: count
		sourceColumn: ProjectPhaseId

		annotation SummarizationSetBy = Automatic

	column ProjectId
		dataType: int64
		formatString: 0
		lineageTag: 595c9999-c348-4ac0-a362-68ad6f30d2cb
		summarizeBy: none
		sourceColumn: ProjectId

		annotation SummarizationSetBy = Automatic

	column ProjectPhaseName
		dataType: string
		lineageTag: 3eea9cfd-2be6-4ec3-b45c-2b363894af0f
		summarizeBy: none
		sourceColumn: ProjectPhaseName

		annotation SummarizationSetBy = Automatic

	column ScheduledStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 96190595-27ba-4481-ae45-ec18edb4ef4b
		summarizeBy: none
		sourceColumn: ScheduledStartDate

		variation Variation
			isDefault
			relationship: 2d0ba156-a8f8-4185-ac5f-600b79125d21
			defaultHierarchy: LocalDateTable_3b73fd6d-9c0f-4422-99dc-8a1fef2257df.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'A08 - Reporting Scheduled Start Date' = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(#"A08_00 - All Phase", {"ProjectPhaseId"}, #"A08_00 - Final Report Issuance Date", {"ProjectPhaseId"}, "A08_00 - Final Report Issuance Date", JoinKind.LeftOuter),
				    #"Expanded A08_00 - Final Report Issuance Date" = Table.ExpandTableColumn(Source, "A08_00 - Final Report Issuance Date", {"MilestoneName", "ActualEndDate"}, {"A08_00 - Final Report Issuance Date.MilestoneName", "A08_00 - Final Report Issuance Date.ActualEndDate"}),
				    #"Merged Queries" = Table.NestedJoin(#"Expanded A08_00 - Final Report Issuance Date", {"ProjectPhaseId"}, #"A08_00 - TeamMate Updated Date", {"ProjectPhaseId"}, "A08_00 - TeamMate Updated Date", JoinKind.LeftOuter),
				    #"Expanded A08_00 - TeamMate Updated Date" = Table.ExpandTableColumn(#"Merged Queries", "A08_00 - TeamMate Updated Date", {"MilestoneName", "ActualEndDate"}, {"A08_00 - TeamMate Updated Date.MilestoneName", "A08_00 - TeamMate Updated Date.ActualEndDate"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded A08_00 - TeamMate Updated Date", each ([ProjectPhaseName] = "3. Reporting")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"SortOrder", "EstStartDate", "EstEndDate", "ActStartDate", "ActEndDate", "IsActive", "EstHours", "ActHours", "IsComplete", "DueDate", "RevisedDueDate", "A08_00 - Final Report Issuance Date.MilestoneName", "A08_00 - TeamMate Updated Date.MilestoneName", "A08_00 - TeamMate Updated Date.ActualEndDate", "A08_00 - Final Report Issuance Date.ActualEndDate", "ScheduledEndDate", "ReviewDueDate", "Project"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

