table 'A08 - Closure Scheduled Start Date'
	lineageTag: 6db97afb-97bb-4396-ad46-c8a433772988

	column ProjectPhaseId
		dataType: int64
		formatString: 0
		lineageTag: 42d18dae-bcc2-4358-8914-449c5573bd1d
		summarizeBy: count
		sourceColumn: ProjectPhaseId

		annotation SummarizationSetBy = Automatic

	column ProjectId
		dataType: int64
		formatString: 0
		lineageTag: 14f0606e-ecfd-446a-bafb-5eea830ba3f2
		summarizeBy: none
		sourceColumn: ProjectId

		annotation SummarizationSetBy = Automatic

	column ProjectPhaseName
		dataType: string
		lineageTag: d72fd891-f0cd-4bd8-93ea-a6045b53932e
		summarizeBy: none
		sourceColumn: ProjectPhaseName

		annotation SummarizationSetBy = Automatic

	column ScheduledStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: caebe1f4-5e12-4e13-aa09-ba7684b4acfc
		summarizeBy: none
		sourceColumn: ScheduledStartDate

		variation Variation
			isDefault
			relationship: 7461f130-0bf8-45a2-93f9-813f7fd80b8d
			defaultHierarchy: LocalDateTable_af3bde70-30f0-4726-9a33-83b15fd26205.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'A08 - Closure Scheduled Start Date' = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(#"A08_00 - All Phase", {"ProjectPhaseId"}, #"A08_00 - Final Report Issuance Date", {"ProjectPhaseId"}, "A08_00 - Final Report Issuance Date", JoinKind.LeftOuter),
				    #"Expanded A08_00 - Final Report Issuance Date" = Table.ExpandTableColumn(Source, "A08_00 - Final Report Issuance Date", {"MilestoneName", "ActualEndDate"}, {"A08_00 - Final Report Issuance Date.MilestoneName", "A08_00 - Final Report Issuance Date.ActualEndDate"}),
				    #"Merged Queries" = Table.NestedJoin(#"Expanded A08_00 - Final Report Issuance Date", {"ProjectPhaseId"}, #"A08_00 - TeamMate Updated Date", {"ProjectPhaseId"}, "A08_00 - TeamMate Updated Date", JoinKind.LeftOuter),
				    #"Expanded A08_00 - TeamMate Updated Date" = Table.ExpandTableColumn(#"Merged Queries", "A08_00 - TeamMate Updated Date", {"MilestoneName", "ActualEndDate"}, {"A08_00 - TeamMate Updated Date.MilestoneName", "A08_00 - TeamMate Updated Date.ActualEndDate"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded A08_00 - TeamMate Updated Date", each ([ProjectPhaseName] = "4. Closure")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"SortOrder", "EstStartDate", "EstEndDate", "ActStartDate", "ActEndDate", "IsActive", "EstHours", "ActHours", "IsComplete", "DueDate", "RevisedDueDate", "A08_00 - Final Report Issuance Date.MilestoneName", "A08_00 - TeamMate Updated Date.MilestoneName", "A08_00 - TeamMate Updated Date.ActualEndDate", "A08_00 - Final Report Issuance Date.ActualEndDate", "ScheduledEndDate", "ReviewDueDate", "Project"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

