table 'A08 - Draft  Report Issuance Date'
	lineageTag: 12176292-f4fc-4f18-9de6-8569b24d4659

	column ProjectPhaseId
		dataType: int64
		formatString: 0
		lineageTag: 5fb0c72b-355f-4b05-ba5d-1d30acdc2b52
		summarizeBy: count
		sourceColumn: ProjectPhaseId

		annotation SummarizationSetBy = Automatic

	column ProjectId
		dataType: int64
		formatString: 0
		lineageTag: d3fd8824-507e-44e2-a4fc-a11e8e377ec0
		summarizeBy: none
		sourceColumn: ProjectId

		annotation SummarizationSetBy = Automatic

	column 'A08_00 - Draft Report Issuance Date.MilestoneName'
		dataType: string
		lineageTag: 1cbcb614-e424-4d35-88db-8520b749cf04
		summarizeBy: none
		sourceColumn: A08_00 - Draft Report Issuance Date.MilestoneName

		annotation SummarizationSetBy = Automatic

	column 'A08_00 - Draft Report Issuance Date.ActualEndDate'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bdcd5ff7-949f-4f52-a21e-9380419e8fdb
		summarizeBy: none
		sourceColumn: A08_00 - Draft Report Issuance Date.ActualEndDate

		variation Variation
			isDefault
			relationship: e994dc8b-1ff7-4cab-b812-d6eebea939a6
			defaultHierarchy: LocalDateTable_c26395c3-53b3-4f2c-a056-771c50d4570a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'A08 - Draft  Report Issuance Date' = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(#"A08_00 - All Phase", {"ProjectPhaseId"}, #"A08_00 - Draft Report Issuance Date", {"ProjectPhaseId"}, "A08_00 - Draft Report Issuance Date", JoinKind.LeftOuter),
				    #"Expanded A08_00 - Draft Report Issuance Date" = Table.ExpandTableColumn(Source, "A08_00 - Draft Report Issuance Date", {"MilestoneName", "ActualEndDate"}, {"A08_00 - Draft Report Issuance Date.MilestoneName", "A08_00 - Draft Report Issuance Date.ActualEndDate"}),
				    #"Merged Queries" = Table.NestedJoin(#"Expanded A08_00 - Draft Report Issuance Date", {"ProjectPhaseId"}, #"A08_00 - TeamMate Updated Date", {"ProjectPhaseId"}, "A08_00 - TeamMate Updated Date", JoinKind.LeftOuter),
				    #"Expanded A08_00 - TeamMate Updated Date" = Table.ExpandTableColumn(#"Merged Queries", "A08_00 - TeamMate Updated Date", {"MilestoneName", "ActualEndDate"}, {"A08_00 - TeamMate Updated Date.MilestoneName", "A08_00 - TeamMate Updated Date.ActualEndDate"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded A08_00 - TeamMate Updated Date", each ([ProjectPhaseName] = "3. Reporting")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"SortOrder", "EstStartDate", "EstEndDate", "ActEndDate", "IsActive", "EstHours", "ActHours", "IsComplete", "DueDate", "RevisedDueDate", "A08_00 - TeamMate Updated Date.MilestoneName", "A08_00 - TeamMate Updated Date.ActualEndDate", "ScheduledEndDate", "ScheduledStartDate", "ReviewDueDate", "Project", "ProjectPhaseName", "ActStartDate"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

