table 'A08 - Final Report Issuance Date'
	lineageTag: 32e0caa6-fa14-442d-9634-fa9acd96aab5

	column ProjectPhaseId
		dataType: int64
		formatString: 0
		lineageTag: faf79d5c-cfb0-492c-91c4-937cfd015500
		summarizeBy: count
		sourceColumn: ProjectPhaseId

		annotation SummarizationSetBy = Automatic

	column ProjectId
		dataType: int64
		formatString: 0
		lineageTag: 4ef9534d-9da9-4a71-aaae-927574ffb1b3
		summarizeBy: none
		sourceColumn: ProjectId

		annotation SummarizationSetBy = Automatic

	column 'A08_00 - Final Report Issuance Date.MilestoneName'
		dataType: string
		lineageTag: a5bffb2f-8984-4f9f-9233-3c7b0514f11e
		summarizeBy: none
		sourceColumn: A08_00 - Final Report Issuance Date.MilestoneName

		annotation SummarizationSetBy = Automatic

	column 'A08_00 - Final Report Issuance Date.ActualEndDate'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cd194890-7637-448b-a2aa-d45d7bb1a775
		summarizeBy: none
		sourceColumn: A08_00 - Final Report Issuance Date.ActualEndDate

		variation Variation
			isDefault
			relationship: 037a1904-56cc-43d7-8dbb-bd17f138f533
			defaultHierarchy: LocalDateTable_c59d190b-75f3-4cd7-bce4-565a6ebcfc0a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'A08 - Final Report Issuance Date' = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(#"A08_00 - All Phase", {"ProjectPhaseId"}, #"A08_00 - Final Report Issuance Date", {"ProjectPhaseId"}, "A08_00 - Final Report Issuance Date", JoinKind.LeftOuter),
				    #"Expanded A08_00 - Final Report Issuance Date" = Table.ExpandTableColumn(Source, "A08_00 - Final Report Issuance Date", {"MilestoneName", "ActualEndDate"}, {"A08_00 - Final Report Issuance Date.MilestoneName", "A08_00 - Final Report Issuance Date.ActualEndDate"}),
				    #"Merged Queries" = Table.NestedJoin(#"Expanded A08_00 - Final Report Issuance Date", {"ProjectPhaseId"}, #"A08_00 - TeamMate Updated Date", {"ProjectPhaseId"}, "A08_00 - TeamMate Updated Date", JoinKind.LeftOuter),
				    #"Expanded A08_00 - TeamMate Updated Date" = Table.ExpandTableColumn(#"Merged Queries", "A08_00 - TeamMate Updated Date", {"MilestoneName", "ActualEndDate"}, {"A08_00 - TeamMate Updated Date.MilestoneName", "A08_00 - TeamMate Updated Date.ActualEndDate"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded A08_00 - TeamMate Updated Date", each ([ProjectPhaseName] = "3. Reporting")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"SortOrder", "EstStartDate", "EstEndDate", "ActEndDate", "IsActive", "EstHours", "ActHours", "IsComplete", "DueDate", "RevisedDueDate", "A08_00 - TeamMate Updated Date.MilestoneName", "A08_00 - TeamMate Updated Date.ActualEndDate", "ScheduledEndDate", "ScheduledStartDate", "ReviewDueDate", "Project", "ProjectPhaseName", "ActStartDate"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

