table 'A11_03 - Calc Score: Inherent'
	lineageTag: 36763bef-615f-4652-bdec-f22053ba1fa9

	column StrategicRiskScoringCalculatedId
		dataType: int64
		formatString: 0
		lineageTag: ada209e7-0712-4155-ae43-54e28b66a22a
		summarizeBy: count
		sourceColumn: StrategicRiskScoringCalculatedId

		annotation SummarizationSetBy = Automatic

	column StrategicRiskId
		dataType: int64
		formatString: 0
		lineageTag: fffd2ec8-8baa-4e67-8e02-f34b63591df8
		summarizeBy: none
		sourceColumn: StrategicRiskId

		annotation SummarizationSetBy = Automatic

	column StrategicRiskTitle
		dataType: string
		lineageTag: cf77b5fa-ea5e-4a7e-b82e-3fff799de1e2
		summarizeBy: none
		sourceColumn: StrategicRiskTitle

		annotation SummarizationSetBy = Automatic

	column CalculatedScoreType
		dataType: string
		lineageTag: c21690fd-450c-440c-b631-3422f58e58ce
		summarizeBy: none
		sourceColumn: CalculatedScoreType

		annotation SummarizationSetBy = Automatic

	column CalculatedScoreValue
		dataType: double
		lineageTag: 88985d95-f051-4448-a5e1-9375f655207f
		summarizeBy: sum
		sourceColumn: CalculatedScoreValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AssessmentId
		dataType: int64
		formatString: 0
		lineageTag: 5aa7bbfe-3c25-4aca-a7ca-19d7e1dc3bfb
		summarizeBy: count
		sourceColumn: AssessmentId

		annotation SummarizationSetBy = Automatic

	column ProjectId
		dataType: int64
		formatString: 0
		lineageTag: b12e83e1-0b86-4521-9973-863418a12653
		summarizeBy: count
		sourceColumn: ProjectId

		annotation SummarizationSetBy = Automatic

	partition 'A11_03 - Calc Score: Inherent' = m
		mode: import
		source =
				let
				    Source = OData.Feed("https://acwapoweria.teammatehosting.com/TeamMate/odata/v1", null, [Implementation="2.0"]),
				    StrategicRiskScoringCalculationsAssessmentProject_table = Source{[Name="StrategicRiskScoringCalculationsAssessmentProject",Signature="table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(StrategicRiskScoringCalculationsAssessmentProject_table, each ([AssessmentId] = 31)),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"StrategicRisk"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns", each ([CalculatedScoreType] = "Inherent"))
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

