table 'A11_04 - Score: Residual Likelihood'
	lineageTag: b56ce4d7-5b9f-4ded-8cdd-ed443491d4fb

	column StrategicRiskScoreId
		dataType: int64
		formatString: 0
		lineageTag: 382488fe-6a24-4749-879b-6f7003a3786d
		summarizeBy: count
		sourceColumn: StrategicRiskScoreId

		annotation SummarizationSetBy = Automatic

	column StrategicRiskId
		dataType: int64
		formatString: 0
		lineageTag: 2d349cf6-905b-4a2e-827e-4085a55860d3
		summarizeBy: none
		sourceColumn: StrategicRiskId

		annotation SummarizationSetBy = Automatic

	column StrategicRiskTitle
		dataType: string
		lineageTag: 27810e30-6913-4c10-a389-025af248b338
		summarizeBy: none
		sourceColumn: StrategicRiskTitle

		annotation SummarizationSetBy = Automatic

	column VariableId
		dataType: int64
		formatString: 0
		lineageTag: 783881e3-bb5d-4cd5-a23e-b9cbf5a84f4e
		summarizeBy: count
		sourceColumn: VariableId

		annotation SummarizationSetBy = Automatic

	column VariableTitle
		dataType: string
		lineageTag: 3210c3d5-7244-46b2-8409-b28b41ce1acc
		summarizeBy: none
		sourceColumn: VariableTitle

		annotation SummarizationSetBy = Automatic

	column ScoreType
		dataType: string
		lineageTag: 4f1ca429-0ffc-4aaa-9470-49ed72ab59d6
		summarizeBy: none
		sourceColumn: ScoreType

		annotation SummarizationSetBy = Automatic

	column MetricTitle
		dataType: string
		lineageTag: 98df6c2c-210e-4628-9815-5d64b973556e
		summarizeBy: none
		sourceColumn: MetricTitle

		annotation SummarizationSetBy = Automatic

	column ScoreLabel
		dataType: string
		lineageTag: c147dc5e-f746-400c-8919-114eef5b488e
		summarizeBy: none
		sourceColumn: ScoreLabel

		annotation SummarizationSetBy = Automatic

	column ScoreValue
		dataType: double
		lineageTag: 2e33daea-8823-4802-8b0b-600e7a8dcb26
		summarizeBy: sum
		sourceColumn: ScoreValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AssessmentId
		dataType: int64
		formatString: 0
		lineageTag: 55ce5aab-bbbc-4e4f-88fb-f201a8a6758d
		summarizeBy: count
		sourceColumn: AssessmentId

		annotation SummarizationSetBy = Automatic

	column ProjectId
		dataType: int64
		formatString: 0
		lineageTag: 4eccae1e-41ef-4d59-a298-ed5ef20d94f3
		summarizeBy: count
		sourceColumn: ProjectId

		annotation SummarizationSetBy = Automatic

	partition 'A11_04 - Score: Residual Likelihood' = m
		mode: import
		source =
				let
				    Source = OData.Feed("https://acwapoweria.teammatehosting.com/TeamMate/odata/v1", null, [Implementation="2.0"]),
				    StrategicRiskScoringValuesAssessmentProject_table = Source{[Name="StrategicRiskScoringValuesAssessmentProject",Signature="table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(StrategicRiskScoringValuesAssessmentProject_table, each ([AssessmentId] = 31)),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"StrategicRisk"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"StrategicRiskScoreId", "StrategicRiskId", "StrategicRiskTitle", "VariableId", "VariableTitle", "ScoreType", "MetricTitle", "ScoreLabel", "ScoreValue", "AssessmentId", "ProjectId"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Reordered Columns", each ([ScoreType] = "Residual") and ([MetricTitle] = "Likelihood"))
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

