table 'A12_00 - Auditable Units - Corporate'
	lineageTag: 4c088012-d181-41f1-b392-5c4fa3614503

	column EntityAssessmentId
		dataType: int64
		formatString: 0
		lineageTag: 6dc644b9-320a-4ef5-b964-c23ed51d9523
		summarizeBy: count
		sourceColumn: EntityAssessmentId

		annotation SummarizationSetBy = Automatic

	column EntityId
		dataType: int64
		formatString: 0
		lineageTag: bf70cf17-fa66-48fe-849a-cff204d417ea
		summarizeBy: count
		sourceColumn: EntityId

		annotation SummarizationSetBy = Automatic

	column EntityTitle
		dataType: string
		lineageTag: a5088bf9-b3dc-4afd-ad31-e3137c09276f
		summarizeBy: none
		sourceColumn: EntityTitle

		annotation SummarizationSetBy = Automatic

	column AssessmentId
		dataType: int64
		formatString: 0
		lineageTag: 161faba4-302e-4d0f-9d41-b0271312d135
		summarizeBy: count
		sourceColumn: AssessmentId

		annotation SummarizationSetBy = Automatic

	column AssessmentTitle
		dataType: string
		lineageTag: 63e56be5-f63a-4db5-b767-680b554180e3
		summarizeBy: none
		sourceColumn: AssessmentTitle

		annotation SummarizationSetBy = Automatic

	column Date2
		dataType: dateTime
		formatString: Long Date
		lineageTag: 45cda782-6201-4f56-ac72-5833770739ea
		summarizeBy: none
		sourceColumn: Date2

		variation Variation
			isDefault
			relationship: 21d3d050-b4a6-49c3-8391-5ac89bd2c545
			defaultHierarchy: LocalDateTable_524f1e04-23c9-4694-ae40-2fa7a34689bb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date3
		dataType: dateTime
		formatString: Long Date
		lineageTag: f641909b-7216-40ac-9473-935e760b0530
		summarizeBy: none
		sourceColumn: Date3

		variation Variation
			isDefault
			relationship: 9161a7ce-023e-4999-90e8-081a9381fbd1
			defaultHierarchy: LocalDateTable_3eddcbfd-04f2-4783-8153-c598ca9eb181.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date4
		dataType: dateTime
		formatString: Long Date
		lineageTag: a112fec9-3501-484b-a41a-eb22af928b2d
		summarizeBy: none
		sourceColumn: Date4

		variation Variation
			isDefault
			relationship: 3d7ebef1-11da-406d-b29c-ad6dab79bd32
			defaultHierarchy: LocalDateTable_795c2c06-bc7b-4606-b723-87e958ebb402.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date5
		dataType: dateTime
		formatString: Long Date
		lineageTag: 998bcfc9-3ebf-49b2-acb8-3fed2bd4d2ab
		summarizeBy: none
		sourceColumn: Date5

		variation Variation
			isDefault
			relationship: a0ebc8ff-0be1-4701-b07b-c978afa6c5fa
			defaultHierarchy: LocalDateTable_4ca24301-3ce5-4244-b115-903e0b6fb291.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date6
		dataType: dateTime
		formatString: Long Date
		lineageTag: 39b2db0c-59a0-4bc4-991f-e985d6ae5500
		summarizeBy: none
		sourceColumn: Date6

		variation Variation
			isDefault
			relationship: 6ec04c2d-a182-4028-a95b-d33074968a45
			defaultHierarchy: LocalDateTable_aff095f9-13e1-4594-97da-c61b67fc122d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YesNo1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e017054e-d25f-4f17-9d62-277d98e46646
		summarizeBy: none
		sourceColumn: YesNo1

		annotation SummarizationSetBy = Automatic

	column YesNo2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ad2b77b1-16d8-4dfd-9cb0-d0b289cf17f8
		summarizeBy: none
		sourceColumn: YesNo2

		annotation SummarizationSetBy = Automatic

	column YesNo3
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0cbdad86-3c49-453e-a869-06f20f24ad7b
		summarizeBy: none
		sourceColumn: YesNo3

		annotation SummarizationSetBy = Automatic

	column YesNo4
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d8ab8af4-fc7a-463b-a9fa-f5c3c9638ae5
		summarizeBy: none
		sourceColumn: YesNo4

		annotation SummarizationSetBy = Automatic

	column YesNo5
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: aeca5233-a7bf-46e5-be16-c7a17c4aad69
		summarizeBy: none
		sourceColumn: YesNo5

		annotation SummarizationSetBy = Automatic

	column AccountBalance
		dataType: double
		lineageTag: 6b64650d-b896-4fc4-a59b-92f2111a86eb
		summarizeBy: sum
		sourceColumn: AccountBalance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue1
		dataType: double
		lineageTag: 407452cc-6027-4ff5-a393-db4881332e83
		summarizeBy: sum
		sourceColumn: NumericValue1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue2
		dataType: double
		lineageTag: cc31a43f-2c63-4865-8d52-5551f2ff0b87
		summarizeBy: sum
		sourceColumn: NumericValue2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue3
		dataType: double
		lineageTag: 913d1dbc-b776-402d-ba33-e945cc2cdc84
		summarizeBy: sum
		sourceColumn: NumericValue3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue4
		dataType: double
		lineageTag: 9bf4c984-1035-4f87-a7d7-51cd0cd7a0df
		summarizeBy: sum
		sourceColumn: NumericValue4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue5
		dataType: double
		lineageTag: 04ba874a-0212-4009-b7f6-b39b06e4b6d6
		summarizeBy: sum
		sourceColumn: NumericValue5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue6
		dataType: double
		lineageTag: e63f4686-6cbb-4831-aba0-44decb621d19
		summarizeBy: sum
		sourceColumn: NumericValue6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue7
		dataType: double
		lineageTag: d84007e0-ea7d-4c1d-a6a8-6d8722f9e2c1
		summarizeBy: sum
		sourceColumn: NumericValue7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue8
		dataType: double
		lineageTag: edcbe01d-d5eb-45ca-a2b4-0c186d0a5a39
		summarizeBy: sum
		sourceColumn: NumericValue8

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue9
		dataType: double
		lineageTag: 196d9f91-d0fe-44b3-8282-af7ab9155b87
		summarizeBy: sum
		sourceColumn: NumericValue9

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue10
		dataType: double
		lineageTag: be0159cc-babf-45de-a155-79eccbb46b50
		summarizeBy: sum
		sourceColumn: NumericValue10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue11
		dataType: double
		lineageTag: ab49ee30-5eb7-4c23-9546-b285189ad942
		summarizeBy: sum
		sourceColumn: NumericValue11

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue12
		dataType: double
		lineageTag: b9bd62ef-3558-4f77-9b65-e224fdeeebdb
		summarizeBy: sum
		sourceColumn: NumericValue12

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue13
		dataType: double
		lineageTag: 158886ea-b695-4597-b236-411051ad065d
		summarizeBy: sum
		sourceColumn: NumericValue13

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue14
		dataType: double
		lineageTag: 456481a3-e80e-42e8-b8fe-4d389f3a3321
		summarizeBy: sum
		sourceColumn: NumericValue14

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue15
		dataType: double
		lineageTag: bb2f53a0-b6ea-44e2-b2d3-b0a48163d3c3
		summarizeBy: sum
		sourceColumn: NumericValue15

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue16
		dataType: double
		lineageTag: b0cdea6d-8a8a-48da-a0aa-22e21337c42f
		summarizeBy: sum
		sourceColumn: NumericValue16

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue17
		dataType: double
		lineageTag: e17ab1a3-4026-4624-b365-a4b069beb032
		summarizeBy: sum
		sourceColumn: NumericValue17

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue18
		dataType: double
		lineageTag: c26d7f56-5249-4f17-a2f7-f259305a9969
		summarizeBy: sum
		sourceColumn: NumericValue18

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue19
		dataType: double
		lineageTag: 65fe1548-90ad-4507-9b7e-549a8a2e7c0a
		summarizeBy: sum
		sourceColumn: NumericValue19

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue20
		dataType: double
		lineageTag: 9660cd3a-5e18-496a-ae65-e834ee333901
		summarizeBy: sum
		sourceColumn: NumericValue20

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue21
		dataType: double
		lineageTag: b99182d4-2022-4f4a-afaf-ded0fd13887a
		summarizeBy: sum
		sourceColumn: NumericValue21

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue22
		dataType: double
		lineageTag: 29fc1365-7f9e-4f88-bc17-665a59b1795e
		summarizeBy: sum
		sourceColumn: NumericValue22

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue23
		dataType: double
		lineageTag: 9df71e48-023c-4844-a8c2-b0095213015c
		summarizeBy: sum
		sourceColumn: NumericValue23

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue24
		dataType: double
		lineageTag: 1d66154f-7de8-4968-bc5c-063395110001
		summarizeBy: sum
		sourceColumn: NumericValue24

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumericValue25
		dataType: double
		lineageTag: 4e51a626-7837-4ce3-8c6c-b814380c0ae2
		summarizeBy: sum
		sourceColumn: NumericValue25

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Category1Id
		dataType: int64
		formatString: 0
		lineageTag: a1c78a7d-767a-4d03-8878-926c1f7ba03a
		summarizeBy: count
		sourceColumn: Category1Id

		annotation SummarizationSetBy = Automatic

	column Category1
		dataType: string
		lineageTag: 439e75c3-79a0-48b6-878d-a8db732a5bff
		summarizeBy: none
		sourceColumn: Category1

		annotation SummarizationSetBy = Automatic

	column Category2Id
		dataType: int64
		formatString: 0
		lineageTag: 20db988d-7c73-442c-a22b-666a5641679f
		summarizeBy: count
		sourceColumn: Category2Id

		annotation SummarizationSetBy = Automatic

	column Category2
		dataType: string
		lineageTag: 32135004-9eca-4ad8-9ce0-89f791998885
		summarizeBy: none
		sourceColumn: Category2

		annotation SummarizationSetBy = Automatic

	column Category3Id
		dataType: int64
		formatString: 0
		lineageTag: f251919a-f076-4058-8954-260d2ae3c0db
		summarizeBy: count
		sourceColumn: Category3Id

		annotation SummarizationSetBy = Automatic

	column Category3
		dataType: string
		lineageTag: 5faaf888-e86f-4821-a36a-4eadf823a215
		summarizeBy: none
		sourceColumn: Category3

		annotation SummarizationSetBy = Automatic

	column Category4Id
		dataType: int64
		formatString: 0
		lineageTag: 90f02343-0645-4bcd-8355-fe9f0e81188b
		summarizeBy: count
		sourceColumn: Category4Id

		annotation SummarizationSetBy = Automatic

	column Category4
		dataType: string
		lineageTag: 04ead29d-2ed4-4c9b-9894-7e797f1bfe21
		summarizeBy: none
		sourceColumn: Category4

		annotation SummarizationSetBy = Automatic

	column Category5Id
		dataType: int64
		formatString: 0
		lineageTag: 6479ad2c-6071-4928-a181-40a6595f265e
		summarizeBy: count
		sourceColumn: Category5Id

		annotation SummarizationSetBy = Automatic

	column Category5
		dataType: string
		lineageTag: 51650287-4c07-42a3-85b8-45b2fab67f7a
		summarizeBy: none
		sourceColumn: Category5

		annotation SummarizationSetBy = Automatic

	column SAPeriodId
		dataType: int64
		formatString: 0
		lineageTag: 74e75b8d-4b16-4d02-89d6-90abd5438f0c
		summarizeBy: count
		sourceColumn: SAPeriodId

		annotation SummarizationSetBy = Automatic

	column SAPeriod
		dataType: string
		lineageTag: 9725283b-cb39-45e6-9b07-e79759734fc5
		summarizeBy: none
		sourceColumn: SAPeriod

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory2Id
		dataType: int64
		formatString: 0
		lineageTag: 035e836a-a521-47a8-9f1b-461fd76edad5
		summarizeBy: count
		sourceColumn: MultiSelectCategory2Id

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory2
		dataType: string
		lineageTag: de9aa8e0-5a6b-4947-82a4-486aae916a2f
		summarizeBy: none
		sourceColumn: MultiSelectCategory2

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory3Id
		dataType: int64
		formatString: 0
		lineageTag: 55786557-4ad5-4686-ad4e-7346463384ad
		summarizeBy: count
		sourceColumn: MultiSelectCategory3Id

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory3
		dataType: string
		lineageTag: 57910850-6260-4ee8-b84d-c9191243828a
		summarizeBy: none
		sourceColumn: MultiSelectCategory3

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory4Id
		dataType: int64
		formatString: 0
		lineageTag: a336545a-ae29-40cb-9745-6b28308b8aa7
		summarizeBy: count
		sourceColumn: MultiSelectCategory4Id

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory4
		dataType: string
		lineageTag: ad998828-bc25-47dd-a58d-cb66dd1e446e
		summarizeBy: none
		sourceColumn: MultiSelectCategory4

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory5Id
		dataType: int64
		formatString: 0
		lineageTag: 8e7205dd-64f5-479e-89a2-ba8991ffb84b
		summarizeBy: count
		sourceColumn: MultiSelectCategory5Id

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory5
		dataType: string
		lineageTag: daea24ba-9e3d-4283-92b4-3c0414b2cb27
		summarizeBy: none
		sourceColumn: MultiSelectCategory5

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory6Id
		dataType: int64
		formatString: 0
		lineageTag: 8bdda7c7-abf1-4fe7-9f34-2f9b7c1a21af
		summarizeBy: count
		sourceColumn: MultiSelectCategory6Id

		annotation SummarizationSetBy = Automatic

	column MultiSelectCategory6
		dataType: string
		lineageTag: 6175fa35-bf53-4a2a-a231-e3ae114df9a1
		summarizeBy: none
		sourceColumn: MultiSelectCategory6

		annotation SummarizationSetBy = Automatic

	partition 'A12_00 - Auditable Units - Corporate' = m
		mode: import
		source =
				let
				    Source = OData.Feed("https://acwapoweria.teammatehosting.com/TeamMate/odata/v1", null, [Implementation="2.0"]),
				    EntityAssessmentDetails_table = Source{[Name="EntityAssessmentDetails",Signature="table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(EntityAssessmentDetails_table, each ([Category3] = "Corporate"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

