table ghe_Gift_Declaration_Responses
	lineageTag: 5c8b5f3b-8ec7-46b5-92d2-7817ac3b8bf6

	column FileSystemObjectType
		dataType: string
		lineageTag: 72c19eb6-ce4f-495f-b9e4-6d3276fdd514
		summarizeBy: none
		sourceColumn: FileSystemObjectType

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 7e455cff-360a-417f-a4d3-bd557518ad6d
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUri
		dataType: string
		lineageTag: 1c5e0d0f-93cf-45da-9b7b-79bd2a8089e2
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUri

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUrl
		dataType: string
		lineageTag: fb3415e6-23df-42b3-ada6-f8c78c0ddce2
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUrl

		annotation SummarizationSetBy = Automatic

	column 'ID.1'
		dataType: string
		lineageTag: 1c52b4f4-578e-498d-b3af-1b65ba6a692e
		summarizeBy: none
		sourceColumn: ID.1

		annotation SummarizationSetBy = Automatic

	column ContentTypeId
		dataType: string
		lineageTag: 104dc0b4-ff37-4815-97f5-eb65665eb74c
		summarizeBy: none
		sourceColumn: ContentTypeId

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 2e932674-7df8-4f64-a880-b4076dec0c88
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b887ed0-e3e4-48a1-9f67-b65caa7dca67
		summarizeBy: none
		sourceColumn: Modified

		variation Variation
			isDefault
			relationship: f44f2290-078e-47ca-b343-ee866f6c98a6
			defaultHierarchy: LocalDateTable_32cdeedd-afbd-4e8c-a1e8-6ac863dd2c4e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: f04dc056-6582-4bfc-84da-0b209b1cc1a6
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 12f8faf9-5392-4d92-b53a-5ab2711e4a86
			defaultHierarchy: LocalDateTable_80608762-ae4a-4a99-9bde-be22688ba163.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: string
		lineageTag: 89954580-3527-4f31-b47c-1ee64fe4d38f
		summarizeBy: none
		sourceColumn: AuthorId

		annotation SummarizationSetBy = Automatic

	column EditorId
		dataType: string
		lineageTag: 80ca3403-bc8a-4ca8-b493-75b8b7780193
		summarizeBy: none
		sourceColumn: EditorId

		annotation SummarizationSetBy = Automatic

	column OData__UIVersionString
		dataType: string
		lineageTag: 55ebb0e4-396d-4c05-8eb4-3ac4fe47f175
		summarizeBy: none
		sourceColumn: OData__UIVersionString

		annotation SummarizationSetBy = Automatic

	column Attachments
		dataType: string
		lineageTag: 0cf2f837-4e83-4159-a2f7-70e86aa54b32
		summarizeBy: none
		sourceColumn: Attachments

		annotation SummarizationSetBy = Automatic

	column GUID
		dataType: string
		lineageTag: 49e2f120-af28-4c2a-abc6-c95c13154415
		summarizeBy: none
		sourceColumn: GUID

		annotation SummarizationSetBy = Automatic

	column ComplianceAssetId
		dataType: string
		lineageTag: 76223ca8-9059-4392-8c00-c369c43e70b9
		summarizeBy: none
		sourceColumn: ComplianceAssetId

		annotation SummarizationSetBy = Automatic

	column Gift_Declaration_LookupId
		dataType: string
		lineageTag: 88c606cc-4205-459d-82fd-4e38d75b6819
		summarizeBy: none
		sourceColumn: Gift_Declaration_LookupId

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 51a59f5e-2cb9-4722-98dd-04e08a5effdc
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column Question_LookupId
		dataType: string
		lineageTag: cc089c9f-5e23-4e97-b271-8ad271d5cdc4
		summarizeBy: none
		sourceColumn: Question_LookupId

		annotation SummarizationSetBy = Automatic

	column Question_Response
		dataType: string
		lineageTag: cda47d58-510b-4d55-beaf-6e16abca4849
		summarizeBy: none
		sourceColumn: Question_Response

		annotation SummarizationSetBy = Automatic

	column Has_Responses
		dataType: string
		lineageTag: 05d144e6-ada0-47c5-a81e-15b0ad771fcc
		summarizeBy: none
		sourceColumn: Has_Responses

		annotation SummarizationSetBy = Automatic

	column Get_Clarification
		dataType: string
		lineageTag: e0e0f374-6e0e-43f5-91f9-f81e73cacbae
		summarizeBy: none
		sourceColumn: Get_Clarification

		annotation SummarizationSetBy = Automatic

	column 'Question_Lookup.Question'
		dataType: string
		lineageTag: 717837f2-969a-42c7-ba16-9575558709a9
		summarizeBy: none
		sourceColumn: Question_Lookup.Question

		annotation SummarizationSetBy = Automatic

	column 'Question_Lookup.Sequence'
		dataType: string
		lineageTag: 3a00aec2-48ac-4640-bd86-8b6c2aae63a3
		summarizeBy: none
		sourceColumn: Question_Lookup.Sequence

		annotation SummarizationSetBy = Automatic

	column 'Question_Lookup.Question_Identifier'
		dataType: string
		lineageTag: 2eaf38e6-58fe-417c-90d3-50cc29ad6270
		summarizeBy: none
		sourceColumn: Question_Lookup.Question_Identifier

		annotation SummarizationSetBy = Automatic

	column OData__ColorTag
		dataType: string
		lineageTag: bd6d031f-835e-4751-ae9f-c1a48bb54373
		summarizeBy: none
		sourceColumn: OData__ColorTag

		annotation SummarizationSetBy = Automatic

	partition ghe_Gift_Declaration_Responses-4e8b6b51-a7f5-4e5f-ae17-3c98d5b1153c = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://acwapi.sharepoint.com/sites/ComplianceSolution-PROD", [Implementation=null, ApiVersion=15]),
				    #"3ee5eb14-8c59-428f-b985-f127f5a0e2ef" = Source{[Id="3ee5eb14-8c59-428f-b985-f127f5a0e2ef"]}[Items],
				    #"Renamed Columns1" = Table.RenameColumns(#"3ee5eb14-8c59-428f-b985-f127f5a0e2ef",{{"ID", "ID.1"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Modified", type datetime}, {"Created", type datetime}}),
				    #"Expanded Question_Lookup" = Table.ExpandRecordColumn(#"Changed Type", "Question_Lookup", {"Question", "Sequence", "Question_Identifier"}, {"Question_Lookup.Question", "Question_Lookup.Sequence", "Question_Lookup.Question_Identifier"})
				in
				    #"Expanded Question_Lookup"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

